//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AnnualIncome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnnualIncome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Enums.Resources.AnnualIncome", typeof(AnnualIncome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $0 - $500.
        /// </summary>
        internal static string _0_500 {
            get {
                return ResourceManager.GetString("_0_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1,600 - $2,500.
        /// </summary>
        internal static string _1_6K_2_5K {
            get {
                return ResourceManager.GetString("_1_6K_2_5K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $12,800 - $19,200.
        /// </summary>
        internal static string _12_8K_19_2K {
            get {
                return ResourceManager.GetString("_12_8K_19_2K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $145,900 - $218,900.
        /// </summary>
        internal static string _145_9K_218_9K {
            get {
                return ResourceManager.GetString("_145_9K_218_9K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $19,200 - $28,800.
        /// </summary>
        internal static string _19_2K_28_8K {
            get {
                return ResourceManager.GetString("_19_2K_28_8K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1,000 - $1,600.
        /// </summary>
        internal static string _1K_1_6K {
            get {
                return ResourceManager.GetString("_1K_1_6K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $2,500 - $3,800.
        /// </summary>
        internal static string _2_5K_3_8K {
            get {
                return ResourceManager.GetString("_2_5K_3_8K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $218,900+.
        /// </summary>
        internal static string _218_9K {
            get {
                return ResourceManager.GetString("_218_9K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $28,800 - $43,200.
        /// </summary>
        internal static string _28_8K_43_2K {
            get {
                return ResourceManager.GetString("_28_8K_43_2K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $3,800 - $5,700.
        /// </summary>
        internal static string _3_8K_5_7K {
            get {
                return ResourceManager.GetString("_3_8K_5_7K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $43,200 - $64,800.
        /// </summary>
        internal static string _43_2K_64_8K {
            get {
                return ResourceManager.GetString("_43_2K_64_8K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $5,700 - $8,500.
        /// </summary>
        internal static string _5_7K_8_5K {
            get {
                return ResourceManager.GetString("_5_7K_8_5K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $500 - $750.
        /// </summary>
        internal static string _500_750 {
            get {
                return ResourceManager.GetString("_500_750", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $64,800 - $97,300.
        /// </summary>
        internal static string _64_8K_97_3K {
            get {
                return ResourceManager.GetString("_64_8K_97_3K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $750 - $1,000.
        /// </summary>
        internal static string _750_1K {
            get {
                return ResourceManager.GetString("_750_1K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $8,500 - $12,800.
        /// </summary>
        internal static string _8_5K_12_8K {
            get {
                return ResourceManager.GetString("_8_5K_12_8K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $97,300 - $145,900.
        /// </summary>
        internal static string _97_3K_145_9K {
            get {
                return ResourceManager.GetString("_97_3K_145_9K", resourceCulture);
            }
        }
    }
}
