//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CareerCluster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CareerCluster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Enums.Resources.CareerCluster", typeof(CareerCluster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agribusiness Systems; Animal Systems; Environmental and Natural Resources Systems; Food Products and Processing Systems; Plant Systems; Power, Structural and Technical Systems;.
        /// </summary>
        public static string AgricultureFoodNaturalResources_Description {
            get {
                return ResourceManager.GetString("AgricultureFoodNaturalResources_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agriculture, Food &amp; Natural Resources.
        /// </summary>
        public static string AgricultureFoodNaturalResources_Group {
            get {
                return ResourceManager.GetString("AgricultureFoodNaturalResources_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agriculture, Food &amp; Natural Resources.
        /// </summary>
        public static string AgricultureFoodNaturalResources_Name {
            get {
                return ResourceManager.GetString("AgricultureFoodNaturalResources_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction; Design and Pre-construction; Maintenance and Operations;.
        /// </summary>
        public static string ArchitectureConstruction_Description {
            get {
                return ResourceManager.GetString("ArchitectureConstruction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skilled &amp; Technical Sciences.
        /// </summary>
        public static string ArchitectureConstruction_Group {
            get {
                return ResourceManager.GetString("ArchitectureConstruction_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture &amp; Construction.
        /// </summary>
        public static string ArchitectureConstruction_Name {
            get {
                return ResourceManager.GetString("ArchitectureConstruction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Services; Business Information Management; Operations Management; Human Resources Management; Management;.
        /// </summary>
        public static string BusinessManagementAdministration_Description {
            get {
                return ResourceManager.GetString("BusinessManagementAdministration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business, Marketing And Management.
        /// </summary>
        public static string BusinessManagementAdministration_Group {
            get {
                return ResourceManager.GetString("BusinessManagementAdministration_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Management &amp; Administration.
        /// </summary>
        public static string BusinessManagementAdministration_Name {
            get {
                return ResourceManager.GetString("BusinessManagementAdministration_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio/Video Technology and Film; Graphic Design; Journalism and Broadcasting; Performing Arts; Printing Technology; Visual Arts; Web and Digital Communications;.
        /// </summary>
        public static string CommunicationArts_Description {
            get {
                return ResourceManager.GetString("CommunicationArts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication &amp; Information Systems.
        /// </summary>
        public static string CommunicationArts_Group {
            get {
                return ResourceManager.GetString("CommunicationArts_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Arts.
        /// </summary>
        public static string CommunicationArts_Name {
            get {
                return ResourceManager.GetString("CommunicationArts_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration and Administrative Support; Professional Support Services; Teaching/Training;.
        /// </summary>
        public static string EducationTraining_Description {
            get {
                return ResourceManager.GetString("EducationTraining_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Sciences And Education.
        /// </summary>
        public static string EducationTraining_Group {
            get {
                return ResourceManager.GetString("EducationTraining_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education &amp; Training.
        /// </summary>
        public static string EducationTraining_Name {
            get {
                return ResourceManager.GetString("EducationTraining_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering and Technology; Energy;.
        /// </summary>
        public static string EnergyEngineering_Description {
            get {
                return ResourceManager.GetString("EnergyEngineering_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skilled &amp; Technical Sciences.
        /// </summary>
        public static string EnergyEngineering_Group {
            get {
                return ResourceManager.GetString("EnergyEngineering_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy &amp; Engineering.
        /// </summary>
        public static string EnergyEngineering_Name {
            get {
                return ResourceManager.GetString("EnergyEngineering_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting; Banking Services; Business Finance; Securities and Investments; Insurance;.
        /// </summary>
        public static string Finance_Description {
            get {
                return ResourceManager.GetString("Finance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business, Marketing And Management.
        /// </summary>
        public static string Finance_Group {
            get {
                return ResourceManager.GetString("Finance_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string Finance_Name {
            get {
                return ResourceManager.GetString("Finance_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Service; Governance; National Security; Planning; Public Management and Administration; Regulation; Revenue and Taxation;.
        /// </summary>
        public static string GovernmentPublicAdministration_Description {
            get {
                return ResourceManager.GetString("GovernmentPublicAdministration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Sciences And Education.
        /// </summary>
        public static string GovernmentPublicAdministration_Group {
            get {
                return ResourceManager.GetString("GovernmentPublicAdministration_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government &amp; Public Administration.
        /// </summary>
        public static string GovernmentPublicAdministration_Name {
            get {
                return ResourceManager.GetString("GovernmentPublicAdministration_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biotechnology Research and Development; Diagnostic Services; Health Informatics; Supportive Services; Therapeutic Services;.
        /// </summary>
        public static string HealthScience_Description {
            get {
                return ResourceManager.GetString("HealthScience_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Sciences.
        /// </summary>
        public static string HealthScience_Group {
            get {
                return ResourceManager.GetString("HealthScience_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Science.
        /// </summary>
        public static string HealthScience_Name {
            get {
                return ResourceManager.GetString("HealthScience_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lodging; Recreation, Amusements, and Attractions; Restaurants and Food and Beverage Services; Travel and Tourism;.
        /// </summary>
        public static string HospitalityTourism_Description {
            get {
                return ResourceManager.GetString("HospitalityTourism_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business, Marketing And Management.
        /// </summary>
        public static string HospitalityTourism_Group {
            get {
                return ResourceManager.GetString("HospitalityTourism_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitality &amp; Tourism.
        /// </summary>
        public static string HospitalityTourism_Name {
            get {
                return ResourceManager.GetString("HospitalityTourism_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Services; Counseling and Mental Health Services; Early Childhood Development and Services; Family and Community Services; Personal Care Services;.
        /// </summary>
        public static string HumanServices_Description {
            get {
                return ResourceManager.GetString("HumanServices_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Sciences And Education.
        /// </summary>
        public static string HumanServices_Group {
            get {
                return ResourceManager.GetString("HumanServices_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Services.
        /// </summary>
        public static string HumanServices_Name {
            get {
                return ResourceManager.GetString("HumanServices_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Science; Computer Science; Database Administration; Information Support and Services; Network Systems; Programming and Software Development; Web Design and Development;.
        /// </summary>
        public static string InformationTechnology_Description {
            get {
                return ResourceManager.GetString("InformationTechnology_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication &amp; Information Systems.
        /// </summary>
        public static string InformationTechnology_Group {
            get {
                return ResourceManager.GetString("InformationTechnology_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Technology.
        /// </summary>
        public static string InformationTechnology_Name {
            get {
                return ResourceManager.GetString("InformationTechnology_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction Services; Emergency and Fire Management Services; Law Enforcement Services; Legal Services; Security and Protective Services;.
        /// </summary>
        public static string LawPublicSafetyCorrectionsSecurity_Description {
            get {
                return ResourceManager.GetString("LawPublicSafetyCorrectionsSecurity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Sciences And Education.
        /// </summary>
        public static string LawPublicSafetyCorrectionsSecurity_Group {
            get {
                return ResourceManager.GetString("LawPublicSafetyCorrectionsSecurity_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law, Public Safety, Corrections &amp; Security.
        /// </summary>
        public static string LawPublicSafetyCorrectionsSecurity_Name {
            get {
                return ResourceManager.GetString("LawPublicSafetyCorrectionsSecurity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health, Safety, and Environmental Assurance; Logistics and Inventory Control; Manufacturing Production Process Development; Maintenance, Installation, and Repair; Production; Quality Assurance;.
        /// </summary>
        public static string Manufacturing_Description {
            get {
                return ResourceManager.GetString("Manufacturing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skilled &amp; Technical Sciences.
        /// </summary>
        public static string Manufacturing_Group {
            get {
                return ResourceManager.GetString("Manufacturing_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing.
        /// </summary>
        public static string Manufacturing_Name {
            get {
                return ResourceManager.GetString("Manufacturing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Communications; Marketing Management; Marketing Research; Merchandising; Professional Selling;.
        /// </summary>
        public static string Marketing_Description {
            get {
                return ResourceManager.GetString("Marketing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business, Marketing And Management.
        /// </summary>
        public static string Marketing_Group {
            get {
                return ResourceManager.GetString("Marketing_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string Marketing_Name {
            get {
                return ResourceManager.GetString("Marketing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the beginning of their career, intern, just studying or even not working at the moment..
        /// </summary>
        public static string NoCareer_Description {
            get {
                return ResourceManager.GetString("NoCareer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No consolidated career.
        /// </summary>
        public static string NoCareer_Name {
            get {
                return ResourceManager.GetString("NoCareer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility and Mobile Equipment Maintenance; Health, Safety, and Environmental Management; Logistics Planning and Management Services; Sales and Services; Transportation Operations; Transportation/Systems Infrastructure Planning, Management, and Regulations; Warehousing and Distribution Center Operations;.
        /// </summary>
        public static string TransportationDistributionLogistics_Description {
            get {
                return ResourceManager.GetString("TransportationDistributionLogistics_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skilled &amp; Technical Sciences.
        /// </summary>
        public static string TransportationDistributionLogistics_Group {
            get {
                return ResourceManager.GetString("TransportationDistributionLogistics_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation, Distribution &amp; Logistics.
        /// </summary>
        public static string TransportationDistributionLogistics_Name {
            get {
                return ResourceManager.GetString("TransportationDistributionLogistics_Name", resourceCulture);
            }
        }
    }
}
