//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Food {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Food() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Enums.Resources.Food", typeof(Food).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to African Cuisine.
        /// </summary>
        internal static string AfricanCuisine {
            get {
                return ResourceManager.GetString("AfricanCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varied dishes focusing on stews, grains, and root vegetables, often seasoned with unique local spices (e.g., Jollof Rice (Nigeria), Injera (Ethiopia), Bobotie (South Africa), Tagine (Morocco), Biltong (South Africa), Fufu (Ghana))..
        /// </summary>
        internal static string AfricanCuisine_Description {
            get {
                return ResourceManager.GetString("AfricanCuisine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian Cuisine.
        /// </summary>
        internal static string AsianCuisine {
            get {
                return ResourceManager.GetString("AsianCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A diverse range of flavors from East and Southeast Asia, featuring rice and noodle dishes (e.g., Sushi (Japan), Pho (Vietnam), Pad Thai (Thailand), Dumplings (China), Ramen (Japan), Satay (Indonesia))..
        /// </summary>
        internal static string AsianCuisine_Description {
            get {
                return ResourceManager.GetString("AsianCuisine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baked Goods.
        /// </summary>
        internal static string BakedGoods {
            get {
                return ResourceManager.GetString("BakedGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wide range of breads, pastries, and sweets that are enjoyed as snacks or desserts (e.g., Croissants (France), Bagels (United States), Scones (United Kingdom), Danish Pastry (Denmark), Brownies (United States), Puff Pastry (France))..
        /// </summary>
        internal static string BakedGoods_Description {
            get {
                return ResourceManager.GetString("BakedGoods_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desserts &amp; Sweets.
        /// </summary>
        internal static string DessertsSweets {
            get {
                return ResourceManager.GetString("DessertsSweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A variety of sweet treats and desserts, showcasing flavors and techniques from around the world (e.g., Tiramisu (Italy), Baklava (Turkey), Mochi (Japan), Crème Brûlée (France), Churros (Spain), Dulce de Leche (Argentina))..
        /// </summary>
        internal static string DessertsSweets_Description {
            get {
                return ResourceManager.GetString("DessertsSweets_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to European Cuisine.
        /// </summary>
        internal static string EuropeanCuisine {
            get {
                return ResourceManager.GetString("EuropeanCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional and modern dishes from various European countries, emphasizing fresh ingredients and unique cooking styles (e.g., Pasta (Italy), Ratatouille (France), Paella (Spain), Sauerbraten (Germany), Borscht (Ukraine), Fish and Chips (United Kingdom))..
        /// </summary>
        internal static string EuropeanCuisine_Description {
            get {
                return ResourceManager.GetString("EuropeanCuisine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Food &amp; Comfort.
        /// </summary>
        internal static string FastFoodComfort {
            get {
                return ResourceManager.GetString("FastFoodComfort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick meals that are typically easy to prepare and satisfy cravings (e.g., Fried Chicken (United States), Pizza (Italy), Fish and Chips (United Kingdom), Nachos (Mexico), Doner Kebab (Turkey), Cheeseburger (United States))..
        /// </summary>
        internal static string FastFoodComfort_Description {
            get {
                return ResourceManager.GetString("FastFoodComfort_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion Cuisine.
        /// </summary>
        internal static string FusionCuisine {
            get {
                return ResourceManager.GetString("FusionCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovative dishes that blend ingredients and cooking techniques from different cultures (e.g., Korean Tacos (United States), Sushi Burritos (United States), Indian Pizza (India), Thai Curry Pizza (United States), Mediterranean Burrito (Global), Banh Mi Burger (Vietnam))..
        /// </summary>
        internal static string FusionCuisine_Description {
            get {
                return ResourceManager.GetString("FusionCuisine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grilled &amp; Barbecue.
        /// </summary>
        internal static string GrilledBarbecue {
            get {
                return ResourceManager.GetString("GrilledBarbecue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dishes that are cooked over an open flame or grill, celebrated for their smoky flavors (e.g., BBQ Ribs (United States), Tandoori Chicken (India), Grilled Fish (Global), Satay (Indonesia), Grilled Vegetables (Mediterranean), Charcoal-Grilled Meat (Korea))..
        /// </summary>
        internal static string GrilledBarbecue_Description {
            get {
                return ResourceManager.GetString("GrilledBarbecue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home-Cooked Traditional.
        /// </summary>
        internal static string HomeCookedTraditional {
            get {
                return ResourceManager.GetString("HomeCookedTraditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family-style meals that reflect cultural heritage and comfort, often made with love (e.g., Roast Chicken (United States), Lasagna (Italy), Curry (India), Borscht (Ukraine), Meatloaf (United States), Goulash (Hungary))..
        /// </summary>
        internal static string HomeCookedTraditional_Description {
            get {
                return ResourceManager.GetString("HomeCookedTraditional_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian &amp; South Asian.
        /// </summary>
        internal static string IndianSouthAsian {
            get {
                return ResourceManager.GetString("IndianSouthAsian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spicy and flavorful dishes, often centered around rice and bread, using a variety of spices (e.g., Biryani (India), Daal (Pakistan), Curry (Bangladesh), Samosas (India), Butter Chicken (India), Chaat (India))..
        /// </summary>
        internal static string IndianSouthAsian_Description {
            get {
                return ResourceManager.GetString("IndianSouthAsian_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin American.
        /// </summary>
        internal static string LatinAmerican {
            get {
                return ResourceManager.GetString("LatinAmerican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrant and flavorful foods reflecting the diverse cultures of Central and South America (e.g., Tacos (Mexico), Empanadas (Argentina), Feijoada (Brazil), Arepas (Venezuela), Ceviche (Peru), Tamales (Mexico))..
        /// </summary>
        internal static string LatinAmerican_Description {
            get {
                return ResourceManager.GetString("LatinAmerican_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediterranean.
        /// </summary>
        internal static string Mediterranean {
            get {
                return ResourceManager.GetString("Mediterranean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light and healthy meals, typically featuring fresh vegetables, grains, and grilled proteins (e.g., Greek Salad (Greece), Hummus (Lebanon), Falafel (Egypt), Tabbouleh (Lebanon), Fattoush (Lebanon), Grilled Octopus (Greece))..
        /// </summary>
        internal static string Mediterranean_Description {
            get {
                return ResourceManager.GetString("Mediterranean_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Eastern &amp; North African.
        /// </summary>
        internal static string MiddleEasternNorthAfrican {
            get {
                return ResourceManager.GetString("MiddleEasternNorthAfrican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich and aromatic dishes characterized by spices and herbs, often featuring grilled meats and hearty grains (e.g., Shawarma (Lebanon), Couscous (Morocco), Tagine (Algeria), Hummus (Israel), Falafel (Egypt), Kebabs (Turkey))..
        /// </summary>
        internal static string MiddleEasternNorthAfrican_Description {
            get {
                return ResourceManager.GetString("MiddleEasternNorthAfrican_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North American.
        /// </summary>
        internal static string NorthAmerican {
            get {
                return ResourceManager.GetString("NorthAmerican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfort foods with a focus on hearty meals, BBQ, and regional specialties (e.g., Burgers (United States), Poutine (Canada), Clam Chowder (United States), BBQ Ribs (United States), Jambalaya (United States), Cornbread (United States))..
        /// </summary>
        internal static string NorthAmerican_Description {
            get {
                return ResourceManager.GetString("NorthAmerican_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savory Snacks &amp; Small Plates.
        /// </summary>
        internal static string SavorySnacksSmallPlates {
            get {
                return ResourceManager.GetString("SavorySnacksSmallPlates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small, flavorful bites that are perfect for sharing or as appetizers (e.g., Tapas (Spain), Dim Sum (China), Mezze Platter (Middle East), Charcuterie Board (France), Antipasto (Italy), Samosas (India))..
        /// </summary>
        internal static string SavorySnacksSmallPlates_Description {
            get {
                return ResourceManager.GetString("SavorySnacksSmallPlates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seafood.
        /// </summary>
        internal static string Seafood {
            get {
                return ResourceManager.GetString("Seafood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dishes focusing on fish and shellfish, celebrated for their freshness and variety (e.g., Ceviche (Peru), Fish Tacos (Mexico), Grilled Salmon (Norway), Lobster Roll (United States), Clam Chowder (United States), Bouillabaisse (France))..
        /// </summary>
        internal static string Seafood_Description {
            get {
                return ResourceManager.GetString("Seafood_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spicy Food.
        /// </summary>
        internal static string SpicyFood {
            get {
                return ResourceManager.GetString("SpicyFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dishes known for their heat and robust flavors, appealing to those who enjoy bold tastes (e.g., Spicy Ramen (Japan), Sichuan Hot Pot (China), Spicy Curry (India), Vindaloo (India), Spicy Tacos (Mexico), Kimchi (Korea))..
        /// </summary>
        internal static string SpicyFood_Description {
            get {
                return ResourceManager.GetString("SpicyFood_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Food.
        /// </summary>
        internal static string StreetFood {
            get {
                return ResourceManager.GetString("StreetFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual, flavorful foods that are often sold by vendors and reflect local tastes (e.g., Pani Puri (India), Hot Dogs (United States), Arepas (Venezuela), Churros (Spain), Gyoza (Japan), Spring Rolls (Vietnam))..
        /// </summary>
        internal static string StreetFood_Description {
            get {
                return ResourceManager.GetString("StreetFood_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegan.
        /// </summary>
        internal static string Vegan {
            get {
                return ResourceManager.GetString("Vegan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completely plant-based meals without any animal products, often creative and flavorful (e.g., Vegan Burgers (United States), Tofu Stir-fry (Thailand), Chickpea Salad (Global), Vegan Chili (United States), Vegan Sushi (Japan), Quinoa Salad (Peru))..
        /// </summary>
        internal static string Vegan_Description {
            get {
                return ResourceManager.GetString("Vegan_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetarian.
        /// </summary>
        internal static string Vegetarian {
            get {
                return ResourceManager.GetString("Vegetarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wide array of plant-based meals, highlighting vegetables, legumes, and grains (e.g., Ratatouille (France), Vegetable Stir-fry (China), Stuffed Peppers (Italy), Caprese Salad (Italy), Lentil Soup (Turkey), Veggie Burger (United States))..
        /// </summary>
        internal static string Vegetarian_Description {
            get {
                return ResourceManager.GetString("Vegetarian_Description", resourceCulture);
            }
        }
    }
}
