//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GenderIdentity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenderIdentity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Enums.Resources.GenderIdentity", typeof(GenderIdentity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person who does not identify with any gender. Often prefers gender-neutral pronouns, such as &apos;they&apos;..
        /// </summary>
        internal static string Agender_Description {
            get {
                return ResourceManager.GetString("Agender_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agender.
        /// </summary>
        internal static string Agender_Name {
            get {
                return ResourceManager.GetString("Agender_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person whose gender identity or expression incorporates both masculine and feminine elements..
        /// </summary>
        internal static string Androgyne_Description {
            get {
                return ResourceManager.GetString("Androgyne_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Androgyne.
        /// </summary>
        internal static string Androgyne_Name {
            get {
                return ResourceManager.GetString("Androgyne_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person who identifies with two genders, either simultaneously or switching between them over time..
        /// </summary>
        internal static string Bigender_Description {
            get {
                return ResourceManager.GetString("Bigender_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bigender.
        /// </summary>
        internal static string Bigender_Name {
            get {
                return ResourceManager.GetString("Bigender_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person whose gender identity aligns with the gender they were assigned at birth..
        /// </summary>
        internal static string Cisgender_Description {
            get {
                return ResourceManager.GetString("Cisgender_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cisgender.
        /// </summary>
        internal static string Cisgender_Name {
            get {
                return ResourceManager.GetString("Cisgender_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person whose gender identity is flexible and can change over time, expressing different genders at different moments..
        /// </summary>
        internal static string Genderfluid_Description {
            get {
                return ResourceManager.GetString("Genderfluid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genderfluid.
        /// </summary>
        internal static string Genderfluid_Name {
            get {
                return ResourceManager.GetString("Genderfluid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An umbrella term for people whose gender expression or identity does not align with societal expectations based on their assigned sex at birth..
        /// </summary>
        internal static string GenderNonconforming_Description {
            get {
                return ResourceManager.GetString("GenderNonconforming_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender-nonconforming.
        /// </summary>
        internal static string GenderNonconforming_Name {
            get {
                return ResourceManager.GetString("GenderNonconforming_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A term used by people who reject traditional gender categories. Often overlaps with &quot;non-binary&quot; and can refer to anyone who is not cisgender..
        /// </summary>
        internal static string Genderqueer_Description {
            get {
                return ResourceManager.GetString("Genderqueer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genderqueer.
        /// </summary>
        internal static string Genderqueer_Name {
            get {
                return ResourceManager.GetString("Genderqueer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person born with physical sex characteristics (such as chromosomes or genitals) that do not fit typical definitions of male or female bodies. Often assigned a gender at birth through medical intervention..
        /// </summary>
        internal static string Intersex_Description {
            get {
                return ResourceManager.GetString("Intersex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersex.
        /// </summary>
        internal static string Intersex_Name {
            get {
                return ResourceManager.GetString("Intersex_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person who does not identify exclusively as male or female. Non-binary people may feel they embody aspects of both genders or neither..
        /// </summary>
        internal static string NonBinary_Description {
            get {
                return ResourceManager.GetString("NonBinary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-binary.
        /// </summary>
        internal static string NonBinary_Name {
            get {
                return ResourceManager.GetString("NonBinary_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person who identifies with many or all genders. &quot;Pangender&quot; is the more commonly used term today..
        /// </summary>
        internal static string Omnigender_Description {
            get {
                return ResourceManager.GetString("Omnigender_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omnigender / Pangender.
        /// </summary>
        internal static string Omnigender_Name {
            get {
                return ResourceManager.GetString("Omnigender_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person who is exploring or uncertain about their gender identity or expression..
        /// </summary>
        internal static string Questioning_Description {
            get {
                return ResourceManager.GetString("Questioning_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questioning.
        /// </summary>
        internal static string Questioning_Name {
            get {
                return ResourceManager.GetString("Questioning_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person whose gender identity differs from the sex they were assigned at birth. Some transgender people transition physically, while others may not. Often referred to as &apos;trans&apos; (e.g., trans woman, trans man)..
        /// </summary>
        internal static string Transgender_Description {
            get {
                return ResourceManager.GetString("Transgender_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transgender (Trans).
        /// </summary>
        internal static string Transgender_Name {
            get {
                return ResourceManager.GetString("Transgender_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A term used in some Indigenous North American cultures to describe a person who embodies both masculine and feminine qualities, often seen as a distinct spiritual role within their communities..
        /// </summary>
        internal static string TwoSpirit_Description {
            get {
                return ResourceManager.GetString("TwoSpirit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Spirit.
        /// </summary>
        internal static string TwoSpirit_Name {
            get {
                return ResourceManager.GetString("TwoSpirit_Name", resourceCulture);
            }
        }
    }
}
