//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Holidays {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Holidays() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Enums.Resources.Holidays", typeof(Holidays).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult Only Holidays.
        /// </summary>
        public static string AdultOnlyHolidays_Name {
            get {
                return ResourceManager.GetString("AdultOnlyHolidays_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the outdoor recreation of carrying personal things on your back while walking for more than a day. It is often, but not always, a long trip and may or may not involve camping outdoors..
        /// </summary>
        public static string Backpacking_Description {
            get {
                return ResourceManager.GetString("Backpacking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backpacking.
        /// </summary>
        public static string Backpacking_Name {
            get {
                return ResourceManager.GetString("Backpacking_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach / Water Sports.
        /// </summary>
        public static string BeachWaterSports_Name {
            get {
                return ResourceManager.GetString("BeachWaterSports_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A place with temporary accommodation of huts, tents or other structures, normally used by soldiers, refugees, prisoners or travelers.
        /// </summary>
        public static string Camping_Description {
            get {
                return ResourceManager.GetString("Camping_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camping.
        /// </summary>
        public static string Camping_Name {
            get {
                return ResourceManager.GetString("Camping_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Break.
        /// </summary>
        public static string CityBreak_Name {
            get {
                return ResourceManager.GetString("CityBreak_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The practice of traveling and staying with people you don&apos;t know, who advertise their homes on the internet.
        /// </summary>
        public static string CouchSurfing_Description {
            get {
                return ResourceManager.GetString("CouchSurfing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couch Surfing.
        /// </summary>
        public static string CouchSurfing_Name {
            get {
                return ResourceManager.GetString("CouchSurfing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countryside Break.
        /// </summary>
        public static string CountrysideBreak_Name {
            get {
                return ResourceManager.GetString("CountrysideBreak_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruise Holidays.
        /// </summary>
        public static string CruiseHolidays_Name {
            get {
                return ResourceManager.GetString("CruiseHolidays_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploring Exotic Adventurous Places.
        /// </summary>
        public static string ExploringExoticAdventurousPlaces_Name {
            get {
                return ResourceManager.GetString("ExploringExoticAdventurousPlaces_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An arrangement where two families switch homes on vacation.
        /// </summary>
        public static string HomeSwap_Description {
            get {
                return ResourceManager.GetString("HomeSwap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Swap.
        /// </summary>
        public static string HomeSwap_Name {
            get {
                return ResourceManager.GetString("HomeSwap_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just Staying Home.
        /// </summary>
        public static string JustStayingHome_Name {
            get {
                return ResourceManager.GetString("JustStayingHome_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lakes / Mountains.
        /// </summary>
        public static string LakesMountains_Name {
            get {
                return ResourceManager.GetString("LakesMountains_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music / Events Festivals.
        /// </summary>
        public static string MusicEventsFestivals_Name {
            get {
                return ResourceManager.GetString("MusicEventsFestivals_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor Sporting Activities.
        /// </summary>
        public static string OutdoorSportingActivities_Name {
            get {
                return ResourceManager.GetString("OutdoorSportingActivities_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaxing / Wellness.
        /// </summary>
        public static string RelaxingWellness_Name {
            get {
                return ResourceManager.GetString("RelaxingWellness_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Ttrips.
        /// </summary>
        public static string RoadTtrips_Name {
            get {
                return ResourceManager.GetString("RoadTtrips_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safaris.
        /// </summary>
        public static string Safaris_Name {
            get {
                return ResourceManager.GetString("Safaris_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport Holidays.
        /// </summary>
        public static string SportHolidays_Name {
            get {
                return ResourceManager.GetString("SportHolidays_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Journeys.
        /// </summary>
        public static string TrainJourneys_Name {
            get {
                return ResourceManager.GetString("TrainJourneys_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visiting Family.
        /// </summary>
        public static string VisitingFamily_Name {
            get {
                return ResourceManager.GetString("VisitingFamily_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visiting Famous Landmarks.
        /// </summary>
        public static string VisitingFamousLandmarks_Name {
            get {
                return ResourceManager.GetString("VisitingFamousLandmarks_Name", resourceCulture);
            }
        }
    }
}
