//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IdealPlaceToLive {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdealPlaceToLive() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Enums.Resources.IdealPlaceToLive", typeof(IdealPlaceToLive).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexible.
        /// </summary>
        internal static string Flexible {
            get {
                return ResourceManager.GetString("Flexible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open to various living situations, prioritizing other factors over location..
        /// </summary>
        internal static string Flexible_Description {
            get {
                return ResourceManager.GetString("Flexible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rural.
        /// </summary>
        internal static string Rural {
            get {
                return ResourceManager.GetString("Rural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values the tranquility and natural beauty of countryside living..
        /// </summary>
        internal static string Rural_Description {
            get {
                return ResourceManager.GetString("Rural_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suburban.
        /// </summary>
        internal static string Suburban {
            get {
                return ResourceManager.GetString("Suburban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoys the charm and community feel of a small town..
        /// </summary>
        internal static string Suburban_Description {
            get {
                return ResourceManager.GetString("Suburban_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urban.
        /// </summary>
        internal static string Urban {
            get {
                return ResourceManager.GetString("Urban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefers the excitement and opportunities of a bustling city environment..
        /// </summary>
        internal static string Urban_Description {
            get {
                return ResourceManager.GetString("Urban_Description", resourceCulture);
            }
        }
    }
}
