//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Intentions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Intentions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Enums.Resources.Intentions", typeof(Intentions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For those who do not intend to officially marry, but still want to live a life together (depending on the laws/cultures in force in the country, this can also entail responsibilities similar to a marriage)..
        /// </summary>
        public static string LiveTogether_Description {
            get {
                return ResourceManager.GetString("LiveTogether_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Together.
        /// </summary>
        public static string LiveTogether_Name {
            get {
                return ResourceManager.GetString("LiveTogether_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For those who intend to marry (bond established between two people, through governmental, cultural, religious and/or social recognition)..
        /// </summary>
        public static string Married_Description {
            get {
                return ResourceManager.GetString("Married_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Married.
        /// </summary>
        public static string Married_Name {
            get {
                return ResourceManager.GetString("Married_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serious dating is when you’re committed to a person. You have feelings for them, and they have feelings for you. Because of this, you’re not seeing anyone else and you hope to one day take the relationship to the next level..
        /// </summary>
        public static string Serious_Description {
            get {
                return ResourceManager.GetString("Serious_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serious Relationship.
        /// </summary>
        public static string Serious_Name {
            get {
                return ResourceManager.GetString("Serious_Name", resourceCulture);
            }
        }
    }
}
