//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MoneyPersonality {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MoneyPersonality() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Enums.Resources.MoneyPersonality", typeof(MoneyPersonality).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You love money (and there&apos;s nothing wrong with that)! You love spending it, primarily on amazing stuff, experiences, and services. You may even enjoy saving it, but with a spending goal in mind. You enjoy the finer things in life, however you define them, and pride yourself on your good taste — it&apos;s all about quality for you. You also work hard for your money, which allows you to feel good about spending it, and treating yourself and others well. You like to enjoy life with all five senses and inviting othe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Connoisseur_Description {
            get {
                return ResourceManager.GetString("Connoisseur_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connoisseur.
        /// </summary>
        public static string Connoisseur_Name {
            get {
                return ResourceManager.GetString("Connoisseur_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s important to you to live life on your own terms and to have the freedom to follow your bliss. You tend not to think about money unless it&apos;s getting in the way of living life the way you want. You resist having money dictate your life choices, and are aware that your choices may not make sense to others around you. Some Independents see money as a game with too many rules and rebel against how others say it must be played. Others have an easy-come-easy-go attitude about money. Because you&apos;re resourceful [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Independent_Description {
            get {
                return ResourceManager.GetString("Independent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent.
        /// </summary>
        public static string Independent_Name {
            get {
                return ResourceManager.GetString("Independent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships come first, so you keep others in mind when making financial decisions (even though sometimes you&apos;re aware that putting others first means unintentionally harming yourself). You love giving and empowering others with both your money and your time. In a relationship or family, being a good provider is a priority for you..
        /// </summary>
        public static string Nurturer_Description {
            get {
                return ResourceManager.GetString("Nurturer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurturer.
        /// </summary>
        public static string Nurturer_Name {
            get {
                return ResourceManager.GetString("Nurturer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You enjoy accumulating money and the process of watching it grow. You&apos;re on top of your finances, paying close attention to what&apos;s coming in and what&apos;s going out — and making decisions about it methodically. You are often financially conservative, taking steps to minimize your exposure to risk, regardless of how much money you have. Sometimes, you find that this cautious stance holds you back from achieving your goals..
        /// </summary>
        public static string Producer_Description {
            get {
                return ResourceManager.GetString("Producer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer.
        /// </summary>
        public static string Producer_Name {
            get {
                return ResourceManager.GetString("Producer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You enjoy accumulating money and the process of watching it grow. You&apos;re on top of your finances, paying close attention to what&apos;s coming in and what&apos;s going out — and making decisions about it methodically. You are often financially conservative, taking steps to minimize your exposure to risk, regardless of how much money you have. Sometimes, you find that this cautious stance holds you back from achieving your goals..
        /// </summary>
        public static string Visionary_Description {
            get {
                return ResourceManager.GetString("Visionary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visionary.
        /// </summary>
        public static string Visionary_Name {
            get {
                return ResourceManager.GetString("Visionary_Name", resourceCulture);
            }
        }
    }
}
