//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MovieGenre {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MovieGenre() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Enums.Resources.MovieGenre", typeof(MovieGenre).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action &amp; Adventure.
        /// </summary>
        internal static string ActionAdventure {
            get {
                return ResourceManager.GetString("ActionAdventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-energy films with exciting sequences and often heroic themes (e.g., action, spy thrillers, survival).
        /// </summary>
        internal static string ActionAdventure_Description {
            get {
                return ResourceManager.GetString("ActionAdventure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        internal static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films that use animated techniques to tell stories, appealing to all ages (e.g., family animation, anime, CGI).
        /// </summary>
        internal static string Animation_Description {
            get {
                return ResourceManager.GetString("Animation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        internal static string Comedy {
            get {
                return ResourceManager.GetString("Comedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light-hearted films intended to entertain and amuse with humor (e.g., romantic comedy, slapstick, dark comedy).
        /// </summary>
        internal static string Comedy_Description {
            get {
                return ResourceManager.GetString("Comedy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentary.
        /// </summary>
        internal static string Documentary {
            get {
                return ResourceManager.GetString("Documentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonfiction films presenting real events, people, or issues in an informative way (e.g., nature docs, true crime, cultural exploration).
        /// </summary>
        internal static string Documentary_Description {
            get {
                return ResourceManager.GetString("Documentary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        internal static string Drama {
            get {
                return ResourceManager.GetString("Drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotionally focused films that explore complex characters and real-life situations (e.g., family drama, social issues, historical drama).
        /// </summary>
        internal static string Drama_Description {
            get {
                return ResourceManager.GetString("Drama_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental &amp; Avant-Garde.
        /// </summary>
        internal static string ExperimentalAvantGarde {
            get {
                return ResourceManager.GetString("ExperimentalAvantGarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nontraditional films that push the boundaries of narrative and form (e.g., surrealism, abstract cinema, art films).
        /// </summary>
        internal static string ExperimentalAvantGarde_Description {
            get {
                return ResourceManager.GetString("ExperimentalAvantGarde_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family &amp; Kids.
        /// </summary>
        internal static string FamilyKids {
            get {
                return ResourceManager.GetString("FamilyKids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films aimed at younger audiences or suitable for family viewing (e.g., family-friendly adventure, animated kids&apos; movies).
        /// </summary>
        internal static string FamilyKids_Description {
            get {
                return ResourceManager.GetString("FamilyKids_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantasy &amp; Mythology.
        /// </summary>
        internal static string FantasyMythology {
            get {
                return ResourceManager.GetString("FantasyMythology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films featuring magical worlds, mythical creatures, and supernatural elements (e.g., epic fantasy, fairy tales, urban fantasy).
        /// </summary>
        internal static string FantasyMythology_Description {
            get {
                return ResourceManager.GetString("FantasyMythology_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical &amp; Biographical.
        /// </summary>
        internal static string HistoricalBiographical {
            get {
                return ResourceManager.GetString("HistoricalBiographical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films based on real events, historical periods, or significant figures (e.g., biographies, war dramas, historical epics).
        /// </summary>
        internal static string HistoricalBiographical_Description {
            get {
                return ResourceManager.GetString("HistoricalBiographical_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror &amp; Thriller.
        /// </summary>
        internal static string HorrorThriller {
            get {
                return ResourceManager.GetString("HorrorThriller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tension-driven films designed to elicit fear or suspense (e.g., psychological horror, supernatural thriller, slasher).
        /// </summary>
        internal static string HorrorThriller_Description {
            get {
                return ResourceManager.GetString("HorrorThriller_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical &amp; Dance.
        /// </summary>
        internal static string MusicalDance {
            get {
                return ResourceManager.GetString("MusicalDance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films where music and dance are central to the storytelling (e.g., musicals, dance movies, rock operas).
        /// </summary>
        internal static string MusicalDance_Description {
            get {
                return ResourceManager.GetString("MusicalDance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery &amp; Crime.
        /// </summary>
        internal static string MysteryCrime {
            get {
                return ResourceManager.GetString("MysteryCrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films focused on solving puzzles, often involving crime or investigation (e.g., detective stories, whodunit, heist).
        /// </summary>
        internal static string MysteryCrime_Description {
            get {
                return ResourceManager.GetString("MysteryCrime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance.
        /// </summary>
        internal static string Romance {
            get {
                return ResourceManager.GetString("Romance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stories centered around romantic relationships and emotional connections (e.g., romantic drama, rom-com, period romance).
        /// </summary>
        internal static string Romance_Description {
            get {
                return ResourceManager.GetString("Romance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science Fiction.
        /// </summary>
        internal static string ScienceFiction {
            get {
                return ResourceManager.GetString("ScienceFiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films exploring futuristic concepts, technology, or alien life (e.g., space opera, dystopian, time travel).
        /// </summary>
        internal static string ScienceFiction_Description {
            get {
                return ResourceManager.GetString("ScienceFiction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western.
        /// </summary>
        internal static string Western {
            get {
                return ResourceManager.GetString("Western", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films set in the American frontier, often exploring themes of justice and survival (e.g., classic westerns, revisionist westerns).
        /// </summary>
        internal static string Western_Description {
            get {
                return ResourceManager.GetString("Western_Description", resourceCulture);
            }
        }
    }
}
