//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MusicGenre {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MusicGenre() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Enums.Resources.MusicGenre", typeof(MusicGenre).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classical &amp; Opera.
        /// </summary>
        internal static string ClassicalOpera {
            get {
                return ResourceManager.GetString("ClassicalOpera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured compositions and orchestral music from various historical periods (e.g., baroque, symphonic, opera).
        /// </summary>
        internal static string ClassicalOpera_Description {
            get {
                return ResourceManager.GetString("ClassicalOpera_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storytelling-driven genre with roots in American folk traditions (e.g., classic country, contemporary country).
        /// </summary>
        internal static string Country_Description {
            get {
                return ResourceManager.GetString("Country_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic &amp; Dance.
        /// </summary>
        internal static string ElectronicDance {
            get {
                return ResourceManager.GetString("ElectronicDance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthesized sounds and beat-heavy tracks for club and festival scenes (e.g., house, techno, trance).
        /// </summary>
        internal static string ElectronicDance_Description {
            get {
                return ResourceManager.GetString("ElectronicDance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental &amp; Avant-Garde.
        /// </summary>
        internal static string ExperimentalAvantGarde {
            get {
                return ResourceManager.GetString("ExperimentalAvantGarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nontraditional music pushing the boundaries of structure and sound (e.g., noise, ambient, minimalist).
        /// </summary>
        internal static string ExperimentalAvantGarde_Description {
            get {
                return ResourceManager.GetString("ExperimentalAvantGarde_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folk &amp; Acoustic.
        /// </summary>
        internal static string FolkAcoustic {
            get {
                return ResourceManager.GetString("FolkAcoustic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music rooted in traditional sounds, often featuring acoustic instruments (e.g., folk, Americana, singer-songwriter).
        /// </summary>
        internal static string FolkAcoustic_Description {
            get {
                return ResourceManager.GetString("FolkAcoustic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gospel &amp; Religious.
        /// </summary>
        internal static string GospelReligious {
            get {
                return ResourceManager.GetString("GospelReligious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music with religious or spiritual themes, often community-oriented (e.g., gospel, hymns, devotional music).
        /// </summary>
        internal static string GospelReligious_Description {
            get {
                return ResourceManager.GetString("GospelReligious_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hip-Hop &amp; Rap.
        /// </summary>
        internal static string HipHopRap {
            get {
                return ResourceManager.GetString("HipHopRap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat-driven music with lyrical flow, storytelling, and social commentary (e.g., rap, trap, old-school hip-hop).
        /// </summary>
        internal static string HipHopRap_Description {
            get {
                return ResourceManager.GetString("HipHopRap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazz &amp; Blues.
        /// </summary>
        internal static string JazzBlues {
            get {
                return ResourceManager.GetString("JazzBlues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich, improvisational genres with roots in African-American history (e.g., jazz, blues, bebop).
        /// </summary>
        internal static string JazzBlues_Description {
            get {
                return ResourceManager.GetString("JazzBlues_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal &amp; Hard Rock.
        /// </summary>
        internal static string MetalHardRock {
            get {
                return ResourceManager.GetString("MetalHardRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intense, amplified sounds often with aggressive tones (e.g., heavy metal, thrash, hard rock).
        /// </summary>
        internal static string MetalHardRock_Description {
            get {
                return ResourceManager.GetString("MetalHardRock_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop &amp; Mainstream.
        /// </summary>
        internal static string PopMainstream {
            get {
                return ResourceManager.GetString("PopMainstream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessible and widely popular music across charts and cultures (e.g., pop, dance-pop, synth-pop).
        /// </summary>
        internal static string PopMainstream_Description {
            get {
                return ResourceManager.GetString("PopMainstream_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;B &amp; Soul.
        /// </summary>
        internal static string RBSoul {
            get {
                return ResourceManager.GetString("RBSoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotional and rhythm-focused music rooted in African-American traditions (e.g., R&amp;B, soul, funk).
        /// </summary>
        internal static string RBSoul_Description {
            get {
                return ResourceManager.GetString("RBSoul_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reggae &amp; World Music.
        /// </summary>
        internal static string ReggaeWorldMusic {
            get {
                return ResourceManager.GetString("ReggaeWorldMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music from diverse cultural origins, often with distinctive rhythms (e.g., reggae, Afrobeat, Latin).
        /// </summary>
        internal static string ReggaeWorldMusic_Description {
            get {
                return ResourceManager.GetString("ReggaeWorldMusic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock &amp; Alternative.
        /// </summary>
        internal static string RockAlternative {
            get {
                return ResourceManager.GetString("RockAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guitar-driven sounds and subgenres with a rebellious edge (e.g., classic rock, punk, indie, grunge).
        /// </summary>
        internal static string RockAlternative_Description {
            get {
                return ResourceManager.GetString("RockAlternative_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soundtracks &amp; Scores.
        /// </summary>
        internal static string SoundtracksScores {
            get {
                return ResourceManager.GetString("SoundtracksScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music composed for visual media, including movies and games (e.g., film scores, video game soundtracks).
        /// </summary>
        internal static string SoundtracksScores_Description {
            get {
                return ResourceManager.GetString("SoundtracksScores_Description", resourceCulture);
            }
        }
    }
}
