//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyersBriggsTypeIndicator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyersBriggsTypeIndicator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Enums.Resources.MyersBriggsTypeIndicator", typeof(MyersBriggsTypeIndicator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protagonists feel at home in relationships and eagerly commit to their chosen partners. They take dating seriously, choosing partners with a long-term view rather than casually. They find great joy in supporting their partner’s goals and intertwining their lives in a committed relationship..
        /// </summary>
        public static string ENFJ_Description {
            get {
                return ResourceManager.GetString("ENFJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomats.
        /// </summary>
        public static string ENFJ_Group {
            get {
                return ResourceManager.GetString("ENFJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protagonist (ENFJ).
        /// </summary>
        public static string ENFJ_Name {
            get {
                return ResourceManager.GetString("ENFJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigners are excited to share life’s insights and experiences with their partners. For them, relationships are a joyful, mutual exploration and a chance to connect deeply. They take relationships seriously and are known for their uninhibited and unwavering devotion to those they love..
        /// </summary>
        public static string ENFP_Description {
            get {
                return ResourceManager.GetString("ENFP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomats.
        /// </summary>
        public static string ENFP_Group {
            get {
                return ResourceManager.GetString("ENFP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigner (ENFP).
        /// </summary>
        public static string ENFP_Name {
            get {
                return ResourceManager.GetString("ENFP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commanders tackle dating and relationships with clear goals and high energy. They like to lead early in relationships, taking responsibility for how things go and working actively to create a rewarding experience for both. Romance is serious business for them, and they come with plenty of experience..
        /// </summary>
        public static string ENTJ_Description {
            get {
                return ResourceManager.GetString("ENTJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysts.
        /// </summary>
        public static string ENTJ_Group {
            get {
                return ResourceManager.GetString("ENTJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander (ENTJ).
        /// </summary>
        public static string ENTJ_Name {
            get {
                return ResourceManager.GetString("ENTJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debaters excel at coming up with endless ideas to keep relationships moving forward. Growth is key for them, and even before dating, they imagine all the ways to explore and evolve together. This can be overwhelming if their partner doesn’t keep up, but when they find someone who shares their love of intellectual adventure, they become an exciting partner..
        /// </summary>
        public static string ENTP_Description {
            get {
                return ResourceManager.GetString("ENTP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysts.
        /// </summary>
        public static string ENTP_Group {
            get {
                return ResourceManager.GetString("ENTP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debater (ENTP).
        /// </summary>
        public static string ENTP_Name {
            get {
                return ResourceManager.GetString("ENTP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consuls highly value social validation and a sense of belonging. Romantic relationships provide significant emotional support and security. For Consuls, strong romantic bonds bring warmth, devotion, and a feeling of stability..
        /// </summary>
        public static string ESFJ_Description {
            get {
                return ResourceManager.GetString("ESFJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinels.
        /// </summary>
        public static string ESFJ_Group {
            get {
                return ResourceManager.GetString("ESFJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consul (ESFJ).
        /// </summary>
        public static string ESFJ_Name {
            get {
                return ResourceManager.GetString("ESFJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainers are sociable, fun-loving, and free-spirited. They live in the moment and extract emotion from everything. Their relationships aren’t about long-term planning but about enjoying bubbly, unpredictable experiences as long as there’s pleasure to be had..
        /// </summary>
        public static string ESFP_Description {
            get {
                return ResourceManager.GetString("ESFP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers.
        /// </summary>
        public static string ESFP_Group {
            get {
                return ResourceManager.GetString("ESFP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainer (ESFP).
        /// </summary>
        public static string ESFP_Name {
            get {
                return ResourceManager.GetString("ESFP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executives maintain consistency from dating through long-term relationships and marriage. They value honesty and openness, are clear about their goals from the start, and expect their partners to follow through. This leads to extremely stable and reliable relationships..
        /// </summary>
        public static string ESTJ_Description {
            get {
                return ResourceManager.GetString("ESTJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinels.
        /// </summary>
        public static string ESTJ_Group {
            get {
                return ResourceManager.GetString("ESTJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive (ESTJ).
        /// </summary>
        public static string ESTJ_Name {
            get {
                return ResourceManager.GetString("ESTJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrepreneurs live life with fun and surprises and enjoy everything in the moment. They may not plan far ahead but their enthusiasm and unpredictability make them exciting dating partners. They often don’t prioritize traditional wedding plans..
        /// </summary>
        public static string ESTP_Description {
            get {
                return ResourceManager.GetString("ESTP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers.
        /// </summary>
        public static string ESTP_Group {
            get {
                return ResourceManager.GetString("ESTP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrepreneur (ESTP).
        /// </summary>
        public static string ESTP_Name {
            get {
                return ResourceManager.GetString("ESTP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advocates tend to take finding a romantic partner seriously. They seek depth and meaning in relationships, refusing to settle for anything less than true love. Finding a compatible partner can take time. Advocates may be seen as demanding or having unrealistic expectations, sometimes hoping for a &apos;perfect&apos; partner or relationship that doesn’t truly exist..
        /// </summary>
        public static string INFJ_Description {
            get {
                return ResourceManager.GetString("INFJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomats.
        /// </summary>
        public static string INFJ_Group {
            get {
                return ResourceManager.GetString("INFJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advocate (INFJ).
        /// </summary>
        public static string INFJ_Name {
            get {
                return ResourceManager.GetString("INFJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediators are dreamers and idealists in romance. The idea of true love resonates deeply with them, and they’re unlikely to be happy with anything less. They often daydream about a perfect relationship and imagine sharing their innermost selves with another person..
        /// </summary>
        public static string INFP_Description {
            get {
                return ResourceManager.GetString("INFP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomats.
        /// </summary>
        public static string INFP_Group {
            get {
                return ResourceManager.GetString("INFP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediator (INFP).
        /// </summary>
        public static string INFP_Name {
            get {
                return ResourceManager.GetString("INFP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architects approach romance like they do most challenges: strategically, with clear goals and a plan to achieve them. In a purely rational world, this would work perfectly. However, love is rarely rational, and Architects may overlook or misinterpret the unpredictable nature of human emotions and affection..
        /// </summary>
        public static string INTJ_Description {
            get {
                return ResourceManager.GetString("INTJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysts.
        /// </summary>
        public static string INTJ_Group {
            get {
                return ResourceManager.GetString("INTJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architect (INTJ).
        /// </summary>
        public static string INTJ_Name {
            get {
                return ResourceManager.GetString("INTJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logicians have a unique mix of traits in romantic relationships that often pleasantly surprise their partners. They are full of ideas but rarely get to explore their romantic thoughts. When they find someone where romance fits, they become excited, enthusiastic, and playful, enjoying intellectual flirting and wordplay..
        /// </summary>
        public static string INTP_Description {
            get {
                return ResourceManager.GetString("INTP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysts.
        /// </summary>
        public static string INTP_Group {
            get {
                return ResourceManager.GetString("INTP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logician (INTP).
        /// </summary>
        public static string INTP_Name {
            get {
                return ResourceManager.GetString("INTP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defenders express kindness through caring deeply for family and home. They provide emotional and practical support whenever needed. For Defenders, home is where the heart is, and they strive to create harmony and beauty in their personal lives..
        /// </summary>
        public static string ISFJ_Description {
            get {
                return ResourceManager.GetString("ISFJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinels.
        /// </summary>
        public static string ISFJ_Group {
            get {
                return ResourceManager.GetString("ISFJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender (ISFJ).
        /// </summary>
        public static string ISFJ_Name {
            get {
                return ResourceManager.GetString("ISFJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventurers are mysterious and emotional but guard their sensitive core carefully. They prefer listening over expressing feelings. They focus on their partners rather than controlling the mood. If accepted as they are, Adventurers prove to be warm and enthusiastic partners..
        /// </summary>
        public static string ISFP_Description {
            get {
                return ResourceManager.GetString("ISFP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers.
        /// </summary>
        public static string ISFP_Group {
            get {
                return ResourceManager.GetString("ISFP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventurer (ISFP).
        /// </summary>
        public static string ISFP_Name {
            get {
                return ResourceManager.GetString("ISFP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logisticians are extremely trustworthy, especially in romantic relationships. They often embody traditional family values, feel comfortable with clear expectations and honesty, and may encourage traditional domestic and gender roles. Though reserved, they are dedicated partners who invest thought and energy into stable, mutually satisfying relationships..
        /// </summary>
        public static string ISTJ_Description {
            get {
                return ResourceManager.GetString("ISTJ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinels.
        /// </summary>
        public static string ISTJ_Group {
            get {
                return ResourceManager.GetString("ISTJ_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistician (ISTJ).
        /// </summary>
        public static string ISTJ_Name {
            get {
                return ResourceManager.GetString("ISTJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romantic relationships with Virtuosos are complex and dynamic, like nailing jelly to a tree. They alternate between coldness and detachment, and passion, spontaneity, and pleasure in the moment. Nothing can be forced; they need space to be themselves but will enjoy the comfort of a stable partner for life..
        /// </summary>
        public static string ISTP_Description {
            get {
                return ResourceManager.GetString("ISTP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers.
        /// </summary>
        public static string ISTP_Group {
            get {
                return ResourceManager.GetString("ISTP_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtuoso (ISTP).
        /// </summary>
        public static string ISTP_Name {
            get {
                return ResourceManager.GetString("ISTP_Name", resourceCulture);
            }
        }
    }
}
