//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReadingGenre {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReadingGenre() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Enums.Resources.ReadingGenre", typeof(ReadingGenre).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A narrative of a person&apos;s life; when the author is also the main subject, this is an autobiography or memoir.
        /// </summary>
        public static string Biography_Description {
            get {
                return ResourceManager.GetString("Biography_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string Biography_Name {
            get {
                return ResourceManager.GetString("Biography_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A magazine that features a serialized story in the form of a comic book, typically featuring the adventures of a superhero..
        /// </summary>
        public static string Comics_Description {
            get {
                return ResourceManager.GetString("Comics_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comics.
        /// </summary>
        public static string Comics_Name {
            get {
                return ResourceManager.GetString("Comics_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A short literary composition that reflects the author&apos;s perspective or point of view.
        /// </summary>
        public static string Essay_Description {
            get {
                return ResourceManager.GetString("Essay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essay.
        /// </summary>
        public static string Essay_Name {
            get {
                return ResourceManager.GetString("Essay_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiction is generally a narrative form, in any medium, consisting of people, events, or places that are imaginary, in other words, not based strictly on history or fact..
        /// </summary>
        public static string FictionGenres_Description {
            get {
                return ResourceManager.GetString("FictionGenres_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiction Genres.
        /// </summary>
        public static string FictionGenres_Name {
            get {
                return ResourceManager.GetString("FictionGenres_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News reporting and current events.
        /// </summary>
        public static string Journalism_Description {
            get {
                return ResourceManager.GetString("Journalism_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journalism.
        /// </summary>
        public static string Journalism_Name {
            get {
                return ResourceManager.GetString("Journalism_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factual story that focuses on a meaningful relationship between the writer and a person, place, or object; reads like a little novel.
        /// </summary>
        public static string Memoir_Description {
            get {
                return ResourceManager.GetString("Memoir_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memoir.
        /// </summary>
        public static string Memoir_Name {
            get {
                return ResourceManager.GetString("Memoir_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factual information about a significant event presented in a format that tells a story.
        /// </summary>
        public static string NarrativeNonfictionPersonalNarrative_Description {
            get {
                return ResourceManager.GetString("NarrativeNonfictionPersonalNarrative_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrative Nonfiction / Personal Narrative.
        /// </summary>
        public static string NarrativeNonfictionPersonalNarrative_Name {
            get {
                return ResourceManager.GetString("NarrativeNonfictionPersonalNarrative_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like a dictionary, thesaurus, encyclopedia, almanac or atlas.
        /// </summary>
        public static string Reference_Description {
            get {
                return ResourceManager.GetString("Reference_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Reference_Name {
            get {
                return ResourceManager.GetString("Reference_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific study report, including in social, natural or other academic disciplines.
        /// </summary>
        public static string ScientificArticle_Description {
            get {
                return ResourceManager.GetString("ScientificArticle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Article.
        /// </summary>
        public static string ScientificArticle_Name {
            get {
                return ResourceManager.GetString("ScientificArticle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information intended to instruct readers in solving personal problems.
        /// </summary>
        public static string SelfHelp_Description {
            get {
                return ResourceManager.GetString("SelfHelp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Help.
        /// </summary>
        public static string SelfHelp_Name {
            get {
                return ResourceManager.GetString("SelfHelp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliable and detailed factual description of a thing.
        /// </summary>
        public static string Textbook_Description {
            get {
                return ResourceManager.GetString("Textbook_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textbook.
        /// </summary>
        public static string Textbook_Name {
            get {
                return ResourceManager.GetString("Textbook_Name", resourceCulture);
            }
        }
    }
}
