//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReadingGenre {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReadingGenre() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Enums.Resources.ReadingGenre", typeof(ReadingGenre).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education &amp; Reference.
        /// </summary>
        internal static string EducationReference {
            get {
                return ResourceManager.GetString("EducationReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informative resources and educational texts for structured learning or reference (e.g., textbooks, guides, encyclopedias).
        /// </summary>
        internal static string EducationReference_Description {
            get {
                return ResourceManager.GetString("EducationReference_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiction &amp; Literature.
        /// </summary>
        internal static string FictionLiterature {
            get {
                return ResourceManager.GetString("FictionLiterature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stories that explore human experiences and imagination, often through narrative prose (e.g., novels, contemporary fiction, classic literature, poetry).
        /// </summary>
        internal static string FictionLiterature_Description {
            get {
                return ResourceManager.GetString("FictionLiterature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History &amp; Biographical.
        /// </summary>
        internal static string HistoryBiographical {
            get {
                return ResourceManager.GetString("HistoryBiographical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts of real historical events, people, and memoirs of personal experiences (e.g., historical fiction, biographies, autobiographies).
        /// </summary>
        internal static string HistoryBiographical_Description {
            get {
                return ResourceManager.GetString("HistoryBiographical_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance &amp; Relationships.
        /// </summary>
        internal static string RomanceRelationships {
            get {
                return ResourceManager.GetString("RomanceRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stories centered on love, connection, and human relationships (e.g., contemporary romance, historical romance, family dramas).
        /// </summary>
        internal static string RomanceRelationships_Description {
            get {
                return ResourceManager.GetString("RomanceRelationships_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science, Nature &amp; Exploration.
        /// </summary>
        internal static string ScienceNatureExploration {
            get {
                return ResourceManager.GetString("ScienceNatureExploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works explaining the natural and scientific world or narrating journeys of exploration (e.g., popular science, environmental studies, travel writing).
        /// </summary>
        internal static string ScienceNatureExploration_Description {
            get {
                return ResourceManager.GetString("ScienceNatureExploration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-Improvement &amp; Mindfulness.
        /// </summary>
        internal static string SelfImprovementMindfulness {
            get {
                return ResourceManager.GetString("SelfImprovementMindfulness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books that focus on self-growth, wellness, and personal insight (e.g., self-help, personal development, mindfulness, spirituality).
        /// </summary>
        internal static string SelfImprovementMindfulness_Description {
            get {
                return ResourceManager.GetString("SelfImprovementMindfulness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Society &amp; Current Affairs.
        /// </summary>
        internal static string SocietyCurrentAffairs {
            get {
                return ResourceManager.GetString("SocietyCurrentAffairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyses and discussions on social, political, and economic issues of our time (e.g., politics, social issues, current events).
        /// </summary>
        internal static string SocietyCurrentAffairs_Description {
            get {
                return ResourceManager.GetString("SocietyCurrentAffairs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speculative &amp; Adventure.
        /// </summary>
        internal static string SpeculativeAdventure {
            get {
                return ResourceManager.GetString("SpeculativeAdventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books that push boundaries through fantasy, science fiction, and adventurous themes (e.g., fantasy, sci-fi, thrillers, mystery, horror, supernatural, adventure).
        /// </summary>
        internal static string SpeculativeAdventure_Description {
            get {
                return ResourceManager.GetString("SpeculativeAdventure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Storytelling.
        /// </summary>
        internal static string VisualStorytelling {
            get {
                return ResourceManager.GetString("VisualStorytelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustrated stories and graphic works that combine art with narrative (e.g., comics, graphic novels, manga).
        /// </summary>
        internal static string VisualStorytelling_Description {
            get {
                return ResourceManager.GetString("VisualStorytelling_Description", resourceCulture);
            }
        }
    }
}
