//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SexPersonality {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SexPersonality() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Enums.Resources.SexPersonality", typeof(SexPersonality).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses sex mainly to relieve stress and relax. After a tough day or high pressure, they seek intimacy to unwind, clear their mind, and often get better sleep. Sex is a way to decompress emotionally and physically..
        /// </summary>
        public static string Decompresser_Description {
            get {
                return ResourceManager.GetString("Decompresser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompresser.
        /// </summary>
        public static string Decompresser_Name {
            get {
                return ResourceManager.GetString("Decompresser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curious and adventurous in bed. Loves trying new things, pushing boundaries, and doesn’t take sex too seriously. Playful, open-minded, and enjoys intellectual and physical exploration during intimacy..
        /// </summary>
        public static string Explorer_Description {
            get {
                return ResourceManager.GetString("Explorer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        public static string Explorer_Name {
            get {
                return ResourceManager.GetString("Explorer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values balance and reciprocity. Open to discussing desires, willing to compromise, and focuses on giving and receiving pleasure equally. Communication about likes and dislikes is key for them..
        /// </summary>
        public static string FairTrader_Description {
            get {
                return ResourceManager.GetString("FairTrader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair Trader.
        /// </summary>
        public static string FairTrader_Name {
            get {
                return ResourceManager.GetString("FairTrader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds pleasure primarily in making their partner feel good. More focused on their partner’s enjoyment than their own, sometimes even uncomfortable receiving pleasure. Very attentive and nurturing in sex..
        /// </summary>
        public static string Giver_Description {
            get {
                return ResourceManager.GetString("Giver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giver.
        /// </summary>
        public static string Giver_Name {
            get {
                return ResourceManager.GetString("Giver_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs sex to feel safe and consensual. Prioritizes trust, comfort, and emotional security before intimacy. May have past trauma or simply values a secure, slow-building connection..
        /// </summary>
        public static string Guardian_Description {
            get {
                return ResourceManager.GetString("Guardian_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian.
        /// </summary>
        public static string Guardian_Name {
            get {
                return ResourceManager.GetString("Guardian_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeks intense, animalistic, and lustful sexual experiences. Lost in raw passion and energy, where time feels suspended. Very physical and uninhibited, aiming for euphoric connection..
        /// </summary>
        public static string PassionPursuer_Description {
            get {
                return ResourceManager.GetString("PassionPursuer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passion Pursuer.
        /// </summary>
        public static string PassionPursuer_Name {
            get {
                return ResourceManager.GetString("PassionPursuer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoys sex for the pure physical sensations. Doesn’t necessarily require emotional connection, just wants to have fun and experience pleasure. Focused on the tactile and erotic aspects..
        /// </summary>
        public static string PleasureSeeker_Description {
            get {
                return ResourceManager.GetString("PleasureSeeker_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleasure Seeker.
        /// </summary>
        public static string PleasureSeeker_Name {
            get {
                return ResourceManager.GetString("PleasureSeeker_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes sex a non-negotiable daily priority. Regardless of tiredness or busy schedules, sex must happen regularly. Prefers routine and consistency in their sex life..
        /// </summary>
        public static string Prioritizer_Description {
            get {
                return ResourceManager.GetString("Prioritizer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritizer.
        /// </summary>
        public static string Prioritizer_Name {
            get {
                return ResourceManager.GetString("Prioritizer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex is deeply emotional and meaningful. Prefers slow, sensual intimacy with eye contact, foreplay, and affirming words. Emotional connection is essential for sexual satisfaction..
        /// </summary>
        public static string Romantic_Description {
            get {
                return ResourceManager.GetString("Romantic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romantic.
        /// </summary>
        public static string Romantic_Name {
            get {
                return ResourceManager.GetString("Romantic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sees sex as a transcendent, almost sacred experience. Combines physical, emotional, and spiritual connection. Practices like tantric sex exemplify this type, focusing on energy and deeper unity..
        /// </summary>
        public static string Spiritualist_Description {
            get {
                return ResourceManager.GetString("Spiritualist_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiritualist.
        /// </summary>
        public static string Spiritualist_Name {
            get {
                return ResourceManager.GetString("Spiritualist_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attracted to taboo and intense experiences. Enjoys BDSM, kinks, fetishes, and pushing sexual boundaries. Loves the excitement of forbidden or unconventional activities..
        /// </summary>
        public static string ThrillSeeker_Description {
            get {
                return ResourceManager.GetString("ThrillSeeker_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrill Seeker.
        /// </summary>
        public static string ThrillSeeker_Name {
            get {
                return ResourceManager.GetString("ThrillSeeker_Name", resourceCulture);
            }
        }
    }
}
