//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Enums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Vacation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Vacation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Enums.Resources.Vacation", typeof(Vacation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure Travel.
        /// </summary>
        internal static string AdventureTravel {
            get {
                return ResourceManager.GetString("AdventureTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-energy and thrill-seeking experiences (e.g., rock climbing, zip-lining, skydiving, paragliding).
        /// </summary>
        internal static string AdventureTravel_Description {
            get {
                return ResourceManager.GetString("AdventureTravel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arts &amp; Festivals.
        /// </summary>
        internal static string ArtsFestivals {
            get {
                return ResourceManager.GetString("ArtsFestivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attending local arts and entertainment events (e.g., music festivals, art shows, theater performances, film festivals).
        /// </summary>
        internal static string ArtsFestivals_Description {
            get {
                return ResourceManager.GetString("ArtsFestivals_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach &amp; Water Activities.
        /// </summary>
        internal static string BeachWaterActivities {
            get {
                return ResourceManager.GetString("BeachWaterActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaxing or adventuring near the water (e.g., beach days, snorkeling, scuba diving, surfing).
        /// </summary>
        internal static string BeachWaterActivities_Description {
            get {
                return ResourceManager.GetString("BeachWaterActivities_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Sightseeing.
        /// </summary>
        internal static string CitySightseeing {
            get {
                return ResourceManager.GetString("CitySightseeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying urban attractions and city-specific experiences (e.g., visiting landmarks, dining at local restaurants, shopping).
        /// </summary>
        internal static string CitySightseeing_Description {
            get {
                return ResourceManager.GetString("CitySightseeing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruises &amp; Boat Tours.
        /// </summary>
        internal static string CruisesBoatTours {
            get {
                return ResourceManager.GetString("CruisesBoatTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploring coastal areas or islands by sea (e.g., river cruises, yacht charters, island-hopping, sunset cruises).
        /// </summary>
        internal static string CruisesBoatTours_Description {
            get {
                return ResourceManager.GetString("CruisesBoatTours_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultural Exploration.
        /// </summary>
        internal static string CulturalExploration {
            get {
                return ResourceManager.GetString("CulturalExploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immersive experiences in local cultures and histories (e.g., museum visits, historical tours, local festivals, heritage sites).
        /// </summary>
        internal static string CulturalExploration_Description {
            get {
                return ResourceManager.GetString("CulturalExploration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eco-Tourism.
        /// </summary>
        internal static string EcoTourism {
            get {
                return ResourceManager.GetString("EcoTourism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustainable travel with a focus on conservation (e.g., eco-lodges, guided nature tours, visiting wildlife sanctuaries).
        /// </summary>
        internal static string EcoTourism_Description {
            get {
                return ResourceManager.GetString("EcoTourism_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family-Friendly Activities.
        /// </summary>
        internal static string FamilyFriendlyActivities {
            get {
                return ResourceManager.GetString("FamilyFriendlyActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities for all ages, often focused on family fun (e.g., theme parks, aquariums, zoos, family beach days).
        /// </summary>
        internal static string FamilyFriendlyActivities_Description {
            get {
                return ResourceManager.GetString("FamilyFriendlyActivities_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food &amp; Culinary Tourism.
        /// </summary>
        internal static string FoodCulinaryTourism {
            get {
                return ResourceManager.GetString("FoodCulinaryTourism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering new cuisines and food experiences (e.g., food tours, local markets, cooking classes, wine and cheese tastings).
        /// </summary>
        internal static string FoodCulinaryTourism_Description {
            get {
                return ResourceManager.GetString("FoodCulinaryTourism_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning &amp; Enrichment.
        /// </summary>
        internal static string LearningEnrichment {
            get {
                return ResourceManager.GetString("LearningEnrichment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel focused on personal growth and skills (e.g., language immersion, photography workshops, historical courses).
        /// </summary>
        internal static string LearningEnrichment_Description {
            get {
                return ResourceManager.GetString("LearningEnrichment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature &amp; Wildlife.
        /// </summary>
        internal static string NatureWildlife {
            get {
                return ResourceManager.GetString("NatureWildlife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities centered around nature and wildlife (e.g., safaris, hiking in national parks, birdwatching, camping).
        /// </summary>
        internal static string NatureWildlife_Description {
            get {
                return ResourceManager.GetString("NatureWildlife_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaxation &amp; Wellness.
        /// </summary>
        internal static string RelaxationWellness {
            get {
                return ResourceManager.GetString("RelaxationWellness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focusing on relaxation and rejuvenation (e.g., spa retreats, yoga retreats, meditation, thermal springs).
        /// </summary>
        internal static string RelaxationWellness_Description {
            get {
                return ResourceManager.GetString("RelaxationWellness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Trips.
        /// </summary>
        internal static string RoadTrips {
            get {
                return ResourceManager.GetString("RoadTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploring multiple destinations by car, often with scenic routes (e.g., cross-country trips, coastal drives, countryside exploring).
        /// </summary>
        internal static string RoadTrips_Description {
            get {
                return ResourceManager.GetString("RoadTrips_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteering Vacations.
        /// </summary>
        internal static string VolunteeringVacations {
            get {
                return ResourceManager.GetString("VolunteeringVacations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traveling with a purpose to help communities or nature (e.g., habitat restoration, wildlife conservation, community support).
        /// </summary>
        internal static string VolunteeringVacations_Description {
            get {
                return ResourceManager.GetString("VolunteeringVacations_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter Sports.
        /// </summary>
        internal static string WinterSports {
            get {
                return ResourceManager.GetString("WinterSports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying seasonal sports and winter landscapes (e.g., skiing, snowboarding, ice skating, snowshoeing).
        /// </summary>
        internal static string WinterSports_Description {
            get {
                return ResourceManager.GetString("WinterSports_Description", resourceCulture);
            }
        }
    }
}
