//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.WEB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.WEB.Resources.GlobalTranslations", typeof(GlobalTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Connection.
        /// </summary>
        public static string ActiveConnection {
            get {
                return ResourceManager.GetString("ActiveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The basic section is mandatory for now. The other sections can be filled in later..
        /// </summary>
        public static string BasicRequired {
            get {
                return ResourceManager.GetString("BasicRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta Version!.
        /// </summary>
        public static string BetaVersion {
            get {
                return ResourceManager.GetString("BetaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only your age will be published. (We use the Gregorian calendar).
        /// </summary>
        public static string BirthdateTip {
            get {
                return ResourceManager.GetString("BirthdateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility.
        /// </summary>
        public static string Compatibility {
            get {
                return ResourceManager.GetString("Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you two are made for each other. This relationship has a bright future ahead of it..
        /// </summary>
        public static string CompatibilityHigh {
            get {
                return ResourceManager.GetString("CompatibilityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, you don&apos;t have much in common. We wish you both the best of luck, as it won&apos;t be an easy task..
        /// </summary>
        public static string CompatibilityLow {
            get {
                return ResourceManager.GetString("CompatibilityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not a perfect couple, but that doesn&apos;t mean that the relationship will fail. Review our report carefully and work through these differences together..
        /// </summary>
        public static string CompatibilityMedium {
            get {
                return ResourceManager.GetString("CompatibilityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To make your profile public, first complete all the steps.
        /// </summary>
        public static string CompleteAllSteps {
            get {
                return ResourceManager.GetString("CompleteAllSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couples.
        /// </summary>
        public static string Couples {
            get {
                return ResourceManager.GetString("Couples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation. Please try again..
        /// </summary>
        public static string CustomVisibilityInvalid {
            get {
                return ResourceManager.GetString("CustomVisibilityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CustomVisibilityLoading {
            get {
                return ResourceManager.GetString("CustomVisibilityLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not available.
        /// </summary>
        public static string CustomVisibilityNoData {
            get {
                return ResourceManager.GetString("CustomVisibilityNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email address.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your partner&apos;s email.
        /// </summary>
        public static string EnterPartnerEmail {
            get {
                return ResourceManager.GetString("EnterPartnerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Compatibility.
        /// </summary>
        public static string ExpectedCompatibility {
            get {
                return ResourceManager.GetString("ExpectedCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for news....
        /// </summary>
        public static string FeatureUnavailableDescription {
            get {
                return ResourceManager.GetString("FeatureUnavailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under development.
        /// </summary>
        public static string FeatureUnavailableMessage {
            get {
                return ResourceManager.GetString("FeatureUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Compatibility.
        /// </summary>
        public static string GeneralCompatibility {
            get {
                return ResourceManager.GetString("GeneralCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to generate a match simulation? This is just to demonstrate how our compatibility system works..
        /// </summary>
        public static string GenerateSimulation {
            get {
                return ResourceManager.GetString("GenerateSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GPS position is not accurate and may result in an incorrect location. If your city is wrong, please try again later or test on another device or browser..
        /// </summary>
        public static string GpsNotAccurate {
            get {
                return ResourceManager.GetString("GpsNotAccurate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will request location for your device (this option must be enabled).
        /// </summary>
        public static string HelpMap {
            get {
                return ResourceManager.GetString("HelpMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will open a popup with multiple choices (along with explanations, if any).
        /// </summary>
        public static string HelpPlus {
            get {
                return ResourceManager.GetString("HelpPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculation is based on research and statistics and may not accurately reflect all cases and/or contexts;.
        /// </summary>
        public static string HelpProfile1 {
            get {
                return ResourceManager.GetString("HelpProfile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions and/or suggestions for improvements, please open a ticket on our support page;.
        /// </summary>
        public static string HelpProfile2 {
            get {
                return ResourceManager.GetString("HelpProfile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will have explanations of each of the items available to choose from..
        /// </summary>
        public static string HelpQuestion {
            get {
                return ResourceManager.GetString("HelpQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Connection.
        /// </summary>
        public static string InactiveConnection {
            get {
                return ResourceManager.GetString("InactiveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation accepted.
        /// </summary>
        public static string InvitationAccepted {
            get {
                return ResourceManager.GetString("InvitationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invitation not accepted.
        /// </summary>
        public static string InvitationNotAccepted {
            get {
                return ResourceManager.GetString("InvitationNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation sent successfully..
        /// </summary>
        public static string InvitationSent {
            get {
                return ResourceManager.GetString("InvitationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite your partner to test your compatibility.
        /// </summary>
        public static string InviteYyourPartnerTitle1 {
            get {
                return ResourceManager.GetString("InviteYyourPartnerTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This invitation will not send an email. If this invitation is not accepted within a period of one month, it will be automatically deleted..
        /// </summary>
        public static string InviteYyourPartnerTitle2 {
            get {
                return ResourceManager.GetString("InviteYyourPartnerTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I trust the platform&apos;s compatibility system and will only select what is non-negotiable for me..
        /// </summary>
        public static string ITrustPlataform {
            get {
                return ResourceManager.GetString("ITrustPlataform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some features need login..
        /// </summary>
        public static string LoginNeeded {
            get {
                return ResourceManager.GetString("LoginNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Relationship.
        /// </summary>
        public static string MyRelationship {
            get {
                return ResourceManager.GetString("MyRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no pending invitations.
        /// </summary>
        public static string NoPendingInvitations {
            get {
                return ResourceManager.GetString("NoPendingInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not answered.
        /// </summary>
        public static string NotAnswered {
            get {
                return ResourceManager.GetString("NotAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled!.
        /// </summary>
        public static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully!.
        /// </summary>
        public static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option not yet available.
        /// </summary>
        public static string OptionNotAvailable {
            get {
                return ResourceManager.GetString("OptionNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Email.
        /// </summary>
        public static string PartnerEmail {
            get {
                return ResourceManager.GetString("PartnerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your partner&apos;s profile is not yet available.
        /// </summary>
        public static string PartnerProfileNotAvailable {
            get {
                return ResourceManager.GetString("PartnerProfileNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This platform is for managing, not streaming..
        /// </summary>
        public static string PlatformForManaging {
            get {
                return ResourceManager.GetString("PlatformForManaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process is constantly evolving. If you would like to report an error or improvement, please open a ticket with our support team..
        /// </summary>
        public static string PopulateFilterDescription {
            get {
                return ResourceManager.GetString("PopulateFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields automatically populated.
        /// </summary>
        public static string PopulateFilterTitle {
            get {
                return ResourceManager.GetString("PopulateFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can define your ideal profile type, so that we can properly calculate your compatibility index.
        /// </summary>
        public static string PreferHelpTopic1 {
            get {
                return ResourceManager.GetString("PreferHelpTopic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The more specific you are in the filters, the less profile options you will have available.
        /// </summary>
        public static string PreferHelpTopic2 {
            get {
                return ResourceManager.GetString("PreferHelpTopic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Feature.
        /// </summary>
        public static string PremiumFeature {
            get {
                return ResourceManager.GetString("PremiumFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product still under development, so a lot will still improve. If you have suggestions to make, please ask in the app&apos;s support section..
        /// </summary>
        public static string ProductUnderDevelopment {
            get {
                return ResourceManager.GetString("ProductUnderDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ensure a positive atmosphere, we take harassment and prejudice seriously. If you encounter such behavior, please report the profile promptly..
        /// </summary>
        public static string ProfileDataBioTip1 {
            get {
                return ResourceManager.GetString("ProfileDataBioTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you find it challenging to interact or recognize harmful intentions, consider reaching out to friends or family for support..
        /// </summary>
        public static string ProfileDataBioTip2 {
            get {
                return ResourceManager.GetString("ProfileDataBioTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more complex personalities, explore tests on specialized sites. Some can be answered just by reading the item descriptions..
        /// </summary>
        public static string ProfileDataPersonTip1 {
            get {
                return ResourceManager.GetString("ProfileDataPersonTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will request location for your device (this option must be enabled).
        /// </summary>
        public static string ProfileHelpMap {
            get {
                return ResourceManager.GetString("ProfileHelpMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will open a popup with multiple choices (along with explanations, if any).
        /// </summary>
        public static string ProfileHelpPlus {
            get {
                return ResourceManager.GetString("ProfileHelpPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will have explanations of each of the items available to choose from..
        /// </summary>
        public static string ProfileHelpQuestion {
            get {
                return ResourceManager.GetString("ProfileHelpQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile not available.
        /// </summary>
        public static string ProfileNotAvailable {
            get {
                return ResourceManager.GetString("ProfileNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile not found or not yet registered properly..
        /// </summary>
        public static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section does not work as a filter, it only complements the profile compatibility calculation..
        /// </summary>
        public static string ProfilePreferPersonTip1 {
            get {
                return ResourceManager.GetString("ProfilePreferPersonTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile is now in private mode and will not be seen or shared with anyone..
        /// </summary>
        public static string ProfilePrivateMode {
            get {
                return ResourceManager.GetString("ProfilePrivateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this first phase, public mode is not yet available. Stay tuned for more news..
        /// </summary>
        public static string PublicModeNotAvailable {
            get {
                return ResourceManager.GetString("PublicModeNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE NOW.
        /// </summary>
        public static string PWAUpdaterButton {
            get {
                return ResourceManager.GetString("PWAUpdaterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available.
        /// </summary>
        public static string PWAUpdaterText {
            get {
                return ResourceManager.GetString("PWAUpdaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account? This action cannot be undone..
        /// </summary>
        public static string SureDeleteAccount {
            get {
                return ResourceManager.GetString("SureDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be honest in the answers given on this form. All information contained herein is open to denouncements and may be evaluated;.
        /// </summary>
        public static string TermTopic1 {
            get {
                return ResourceManager.GetString("TermTopic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be aware of how your data will be treated, we ask you to read our.
        /// </summary>
        public static string TermTopic2 {
            get {
                return ResourceManager.GetString("TermTopic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to detect a GPS system on your device. Please try again or release access to your device&apos;s GPS..
        /// </summary>
        public static string UnableDetectGps {
            get {
                return ResourceManager.GetString("UnableDetectGps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation errors were detected.
        /// </summary>
        public static string ValidationErrorsDetected {
            get {
                return ResourceManager.GetString("ValidationErrorsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why is it important?.
        /// </summary>
        public static string WhyImportant {
            get {
                return ResourceManager.GetString("WhyImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us reach a larger audience..
        /// </summary>
        public static string WriteReviewMessage {
            get {
                return ResourceManager.GetString("WriteReviewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a review.
        /// </summary>
        public static string WriteReviewTitle {
            get {
                return ResourceManager.GetString("WriteReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current location:.
        /// </summary>
        public static string YourCurrentLocation {
            get {
                return ResourceManager.GetString("YourCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your partner&apos;s profile.
        /// </summary>
        public static string YourPartnerProfile {
            get {
                return ResourceManager.GetString("YourPartnerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile (or preferences).
        /// </summary>
        public static string YourProfile {
            get {
                return ResourceManager.GetString("YourProfile", resourceCulture);
            }
        }
    }
}
