//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.WEB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Landing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Landing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.WEB.Resources.Landing", typeof(Landing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility System.
        /// </summary>
        public static string Approach01 {
            get {
                return ResourceManager.GetString("Approach01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We suggest matches using our compatibility system that evaluates values, lifestyle, and relationship goals..
        /// </summary>
        public static string Approach01Desc {
            get {
                return ResourceManager.GetString("Approach01Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intentional Connections.
        /// </summary>
        public static string Approach02 {
            get {
                return ResourceManager.GetString("Approach02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our platform is designed to support serious relationships by focusing on meaningful introductions rather than casual browsing..
        /// </summary>
        public static string Approach02Desc {
            get {
                return ResourceManager.GetString("Approach02Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Profiles.
        /// </summary>
        public static string Approach03 {
            get {
                return ResourceManager.GetString("Approach03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity and photo verification are required before interaction to help ensure authenticity and trust..
        /// </summary>
        public static string Approach03Desc {
            get {
                return ResourceManager.GetString("Approach03Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy and Security.
        /// </summary>
        public static string Approach04 {
            get {
                return ResourceManager.GetString("Approach04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our platform protects your data and provides a secure environment for all users, giving you confidence while connecting..
        /// </summary>
        public static string Approach04Desc {
            get {
                return ResourceManager.GetString("Approach04Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparks Currency.
        /// </summary>
        public static string Approach05 {
            get {
                return ResourceManager.GetString("Approach05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparks are our virtual currency used to access premium actions and features across the platform..
        /// </summary>
        public static string Approach05Desc {
            get {
                return ResourceManager.GetString("Approach05Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Features Ahead.
        /// </summary>
        public static string Approach06 {
            get {
                return ResourceManager.GetString("Approach06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As the platform grows, new matchmaking features and enhancements will be unlocked for more ways to connect..
        /// </summary>
        public static string Approach06Desc {
            get {
                return ResourceManager.GetString("Approach06Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility Report.
        /// </summary>
        public static string CompatibilityReport {
            get {
                return ResourceManager.GetString("CompatibilityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For each match (or couple), we have a complete analysis of each of our categories, with tips, suggestions for improvements and how to deal with your partner in a better way..
        /// </summary>
        public static string CompatibilityReportDesc {
            get {
                return ResourceManager.GetString("CompatibilityReportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility System.
        /// </summary>
        public static string CompatibilitySystem {
            get {
                return ResourceManager.GetString("CompatibilitySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have developed the most advanced and scientifically backed compatibility system to create meaningful, long-lasting relationships..
        /// </summary>
        public static string CompatibilitySystemDesc {
            get {
                return ResourceManager.GetString("CompatibilitySystemDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Approach.
        /// </summary>
        public static string OurApproach {
            get {
                return ResourceManager.GetString("OurApproach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Numbers.
        /// </summary>
        public static string OurNumbers {
            get {
                return ResourceManager.GetString("OurNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Together we are building something amazing!.
        /// </summary>
        public static string OurNumbersMsg1 {
            get {
                return ResourceManager.GetString("OurNumbersMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our numbers are growing every day. Join our community and find your perfect match..
        /// </summary>
        public static string OurNumbersMsg2 {
            get {
                return ResourceManager.GetString("OurNumbersMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Roadmap.
        /// </summary>
        public static string OurRoadmap {
            get {
                return ResourceManager.GetString("OurRoadmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Features Unlocked as Our Community Expands!.
        /// </summary>
        public static string OurRoadmapMsg1 {
            get {
                return ResourceManager.GetString("OurRoadmapMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are constantly evolving! Features may be released early if development is completed ahead of schedule. We appreciate your feedback, and your suggestions can help shape the future of our platform!.
        /// </summary>
        public static string OurRoadmapMsg2 {
            get {
                return ResourceManager.GetString("OurRoadmapMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join our matchmaking pool.
        /// </summary>
        public static string Phase1Opt1 {
            get {
                return ResourceManager.GetString("Phase1Opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore our compatibility system.
        /// </summary>
        public static string Phase1Opt2 {
            get {
                return ResourceManager.GetString("Phase1Opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparks: US$1 per unit.
        /// </summary>
        public static string Phase1Opt3 {
            get {
                return ResourceManager.GetString("Phase1Opt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 1 (0-10k users).
        /// </summary>
        public static string Phase1Title {
            get {
                return ResourceManager.GetString("Phase1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users can apply as matchmaking clients.
        /// </summary>
        public static string Phase2Opt1 {
            get {
                return ResourceManager.GetString("Phase2Opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparks: US$2 per unit.
        /// </summary>
        public static string Phase2Opt3 {
            get {
                return ResourceManager.GetString("Phase2Opt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 2 (10k-20k users).
        /// </summary>
        public static string Phase2Title {
            get {
                return ResourceManager.GetString("Phase2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotlight - Boost your profile on the platform..
        /// </summary>
        public static string Phase3Opt1 {
            get {
                return ResourceManager.GetString("Phase3Opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparks: US$3 per unit.
        /// </summary>
        public static string Phase3Opt2 {
            get {
                return ResourceManager.GetString("Phase3Opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 3 (20k-30k users).
        /// </summary>
        public static string Phase3Title {
            get {
                return ResourceManager.GetString("Phase3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New features to be announced.
        /// </summary>
        public static string Phase4Opt1 {
            get {
                return ResourceManager.GetString("Phase4Opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparks: US$4 per unit.
        /// </summary>
        public static string Phase4Opt2 {
            get {
                return ResourceManager.GetString("Phase4Opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 4 (30k-40k users).
        /// </summary>
        public static string Phase4Title {
            get {
                return ResourceManager.GetString("Phase4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Joined.
        /// </summary>
        public static string RecentlyJoined {
            get {
                return ResourceManager.GetString("RecentlyJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Users.
        /// </summary>
        public static string TotalUsers {
            get {
                return ResourceManager.GetString("TotalUsers", resourceCulture);
            }
        }
    }
}
