//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.WEB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Landing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Landing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.WEB.Resources.Landing", typeof(Landing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticity.
        /// </summary>
        public static string Authenticity {
            get {
                return ResourceManager.GetString("Authenticity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before any interaction, identity and photo verification are mandatory. Users can provide private or public feedback at any time..
        /// </summary>
        public static string AuthenticityDesc {
            get {
                return ResourceManager.GetString("AuthenticityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility Report.
        /// </summary>
        public static string CompatibilityReport {
            get {
                return ResourceManager.GetString("CompatibilityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For each match (or couple), we have a complete analysis of each of our categories, with tips, suggestions for improvements and how to deal with your partner in a better way..
        /// </summary>
        public static string CompatibilityReportDesc {
            get {
                return ResourceManager.GetString("CompatibilityReportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility System.
        /// </summary>
        public static string CompatibilitySystem {
            get {
                return ResourceManager.GetString("CompatibilitySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have developed the most advanced and scientifically backed compatibility system to create meaningful, long-lasting relationships..
        /// </summary>
        public static string CompatibilitySystemDesc {
            get {
                return ResourceManager.GetString("CompatibilitySystemDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couple Compatibility.
        /// </summary>
        public static string CoupleCompatibility {
            get {
                return ResourceManager.GetString("CoupleCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couples can test their compatibility and receive a detailed report with personalized insights and areas for growth..
        /// </summary>
        public static string CoupleCompatibilityDesc {
            get {
                return ResourceManager.GetString("CoupleCompatibilityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM Coin.
        /// </summary>
        public static string MMCoin {
            get {
                return ResourceManager.GetString("MMCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our virtual currency. It will be used for all premium operations, including receiving match suggestions. New features will be developed and announced soon..
        /// </summary>
        public static string MMCoinDesc {
            get {
                return ResourceManager.GetString("MMCoinDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Features.
        /// </summary>
        public static string OurFeatures {
            get {
                return ResourceManager.GetString("OurFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Numbers.
        /// </summary>
        public static string OurNumbers {
            get {
                return ResourceManager.GetString("OurNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Together we are building something amazing!.
        /// </summary>
        public static string OurNumbersMsg1 {
            get {
                return ResourceManager.GetString("OurNumbersMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our numbers are growing every day. Join our community and find your perfect match..
        /// </summary>
        public static string OurNumbersMsg2 {
            get {
                return ResourceManager.GetString("OurNumbersMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Roadmap.
        /// </summary>
        public static string OurRoadmap {
            get {
                return ResourceManager.GetString("OurRoadmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Features Unlocked as Our Community Expands!.
        /// </summary>
        public static string OurRoadmapMsg1 {
            get {
                return ResourceManager.GetString("OurRoadmapMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are constantly evolving! Features may be released earlier for specific countries (once they reach 10k users) or if development is completed ahead of schedule. We welcome your feedback—your suggestions can help shape the future of our platform!.
        /// </summary>
        public static string OurRoadmapMsg2 {
            get {
                return ResourceManager.GetString("OurRoadmapMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join our matchmaking pool.
        /// </summary>
        public static string Phase1Opt1 {
            get {
                return ResourceManager.GetString("Phase1Opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore our compatibility system.
        /// </summary>
        public static string Phase1Opt2 {
            get {
                return ResourceManager.GetString("Phase1Opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couples: Get detailed relationship analysis.
        /// </summary>
        public static string Phase1Opt3 {
            get {
                return ResourceManager.GetString("Phase1Opt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 1 (0-100k users).
        /// </summary>
        public static string Phase1Title {
            get {
                return ResourceManager.GetString("Phase1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users can apply as matchmaking clients.
        /// </summary>
        public static string Phase2Opt1 {
            get {
                return ResourceManager.GetString("Phase2Opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All modules of our plataform released.
        /// </summary>
        public static string Phase2Opt2 {
            get {
                return ResourceManager.GetString("Phase2Opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM Coin: US$1 per unit.
        /// </summary>
        public static string Phase2Opt3 {
            get {
                return ResourceManager.GetString("Phase2Opt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 2 (100k-200k users).
        /// </summary>
        public static string Phase2Title {
            get {
                return ResourceManager.GetString("Phase2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New features to be announced.
        /// </summary>
        public static string Phase3Opt1 {
            get {
                return ResourceManager.GetString("Phase3Opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM Coin: US$2 per unit.
        /// </summary>
        public static string Phase3Opt2 {
            get {
                return ResourceManager.GetString("Phase3Opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 3 (200k-300k users).
        /// </summary>
        public static string Phase3Title {
            get {
                return ResourceManager.GetString("Phase3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New features to be announced.
        /// </summary>
        public static string Phase4Opt1 {
            get {
                return ResourceManager.GetString("Phase4Opt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM Coin: US$3 per unit.
        /// </summary>
        public static string Phase4Opt2 {
            get {
                return ResourceManager.GetString("Phase4Opt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase 4 (300k-400k users).
        /// </summary>
        public static string Phase4Title {
            get {
                return ResourceManager.GetString("Phase4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We care about everyone&apos;s privacy. We have several mechanisms and settings in place to protect your privacy in a way that best suits you..
        /// </summary>
        public static string PrivacyDesc {
            get {
                return ResourceManager.GetString("PrivacyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We develop a complete and scientifically relevant profile to detect true compatibilities within a stable and long-term relationship..
        /// </summary>
        public static string ProfileDesc {
            get {
                return ResourceManager.GetString("ProfileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Joined.
        /// </summary>
        public static string RecentlyJoined {
            get {
                return ResourceManager.GetString("RecentlyJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do not store or exchange information with third parties (or in any other way) that may compromise your security or your data..
        /// </summary>
        public static string SecurityDesc {
            get {
                return ResourceManager.GetString("SecurityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Users.
        /// </summary>
        public static string TotalUsers {
            get {
                return ResourceManager.GetString("TotalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string Tracking {
            get {
                return ResourceManager.GetString("Tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We support you at every step of your matchmaking journey — including first meetings — ensuring a safe and meaningful path to a lasting relationship..
        /// </summary>
        public static string TrackingDesc {
            get {
                return ResourceManager.GetString("TrackingDesc", resourceCulture);
            }
        }
    }
}
