//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Models.Profile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProfileRelationshipModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileRelationshipModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Models.Profile.Resources.ProfileRelationshipModel", typeof(ProfileRelationshipModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Resolution Style.
        /// </summary>
        internal static string ConflictResolutionStyle {
            get {
                return ResourceManager.GetString("ConflictResolutionStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household Management.
        /// </summary>
        internal static string HouseholdManagement {
            get {
                return ResourceManager.GetString("HouseholdManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opposite-Sex Friendships.
        /// </summary>
        internal static string OppositeSexFriendships {
            get {
                return ResourceManager.GetString("OppositeSexFriendships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How I deal with my partner&apos;s friendships.
        /// </summary>
        internal static string OppositeSexFriendships_Description {
            get {
                return ResourceManager.GetString("OppositeSexFriendships_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Finances.
        /// </summary>
        internal static string SharedFinances {
            get {
                return ResourceManager.GetString("SharedFinances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Together Preference.
        /// </summary>
        internal static string TimeTogetherPreference {
            get {
                return ResourceManager.GetString("TimeTogetherPreference", resourceCulture);
            }
        }
    }
}
