//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Models.Profile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfileValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Models.Profile.Resources.ProfileValidation", typeof(ProfileValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Income.
        /// </summary>
        public static string AnnualIncome {
            get {
                return ResourceManager.GetString("AnnualIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A specialized and independent platform will be used.
        /// </summary>
        public static string AnnualIncomeDesc {
            get {
                return ResourceManager.GetString("AnnualIncomeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s necessary if you want to use this field as a filter..
        /// </summary>
        public static string AnnualIncomeWhy {
            get {
                return ResourceManager.GetString("AnnualIncomeWhy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A photo of you will be taken to compare with your gallery.
        /// </summary>
        public static string GalleryDesc {
            get {
                return ResourceManager.GetString("GalleryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary before you publish your profile..
        /// </summary>
        public static string GalleryWhy {
            get {
                return ResourceManager.GetString("GalleryWhy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        public static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A specialized and independent platform will be used.
        /// </summary>
        public static string IdentityDesc {
            get {
                return ResourceManager.GetString("IdentityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary before any interaction with another user..
        /// </summary>
        public static string IdentityWhy {
            get {
                return ResourceManager.GetString("IdentityWhy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Worth.
        /// </summary>
        public static string NetWorth {
            get {
                return ResourceManager.GetString("NetWorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A specialized and independent platform will be used.
        /// </summary>
        public static string NetWorthDesc {
            get {
                return ResourceManager.GetString("NetWorthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s necessary if you want to use this field as a filter..
        /// </summary>
        public static string NetWorthWhy {
            get {
                return ResourceManager.GetString("NetWorthWhy", resourceCulture);
            }
        }
    }
}
