//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Models.Profile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfileBioModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileBioModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Models.Profile.Resources.ProfileBioModel", typeof(ProfileBioModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age_Name {
            get {
                return ResourceManager.GetString("Age_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate_Name {
            get {
                return ResourceManager.GetString("BirthDate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Type.
        /// </summary>
        public static string BodyType {
            get {
                return ResourceManager.GetString("BodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabilities.
        /// </summary>
        public static string Disabilities_Name {
            get {
                return ResourceManager.GetString("Disabilities_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnicity.
        /// </summary>
        public static string Ethnicity {
            get {
                return ResourceManager.GetString("Ethnicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height_Name {
            get {
                return ResourceManager.GetString("Height_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neurodiversity.
        /// </summary>
        public static string Neurodiversity_Name {
            get {
                return ResourceManager.GetString("Neurodiversity_Name", resourceCulture);
            }
        }
    }
}
