//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Translations.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Category {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Category() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Translations.Enum.Category", typeof(Category).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dating Profile Basics: Identity, Location &amp; Personal Details.
        /// </summary>
        public static string BASIC {
            get {
                return ResourceManager.GetString("BASIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how identity, location, languages, relationship status and personal details can influence dating compatibility..
        /// </summary>
        public static string BASIC_Description {
            get {
                return ResourceManager.GetString("BASIC_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity, Location &amp; Personal Details.
        /// </summary>
        public static string BASIC_ShortName {
            get {
                return ResourceManager.GetString("BASIC_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dating Profile &amp; Relationship Tips: Personal Traits.
        /// </summary>
        public static string BIO {
            get {
                return ResourceManager.GetString("BIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore how appearance, age, body type, neurodiversity and disabilities can shape preferences and relationship compatibility..
        /// </summary>
        public static string BIO_Description {
            get {
                return ResourceManager.GetString("BIO_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Traits.
        /// </summary>
        public static string BIO_ShortName {
            get {
                return ResourceManager.GetString("BIO_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dating Profile &amp; Relationship Tips: Relationship Goals.
        /// </summary>
        public static string GOAL {
            get {
                return ResourceManager.GetString("GOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how relationship intentions, children, relocation and preferred living environments can shape long term compatibility..
        /// </summary>
        public static string GOAL_Description {
            get {
                return ResourceManager.GetString("GOAL_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Goals.
        /// </summary>
        public static string GOAL_ShortName {
            get {
                return ResourceManager.GetString("GOAL_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dating Profile &amp; Relationship Tips: Interests &amp; Hobbies.
        /// </summary>
        public static string INTEREST {
            get {
                return ResourceManager.GetString("INTEREST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover how food, travel, sports, entertainment and hobbies can create shared experiences and strengthen relationships..
        /// </summary>
        public static string INTEREST_Description {
            get {
                return ResourceManager.GetString("INTEREST_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interests &amp; Hobbies.
        /// </summary>
        public static string INTEREST_ShortName {
            get {
                return ResourceManager.GetString("INTEREST_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dating Profile &amp; Relationship Tips: Lifestyle &amp; Values.
        /// </summary>
        public static string LIFESTYLE {
            get {
                return ResourceManager.GetString("LIFESTYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understand how habits, family, religion, finances, career and lifestyle choices can affect long term relationship compatibility..
        /// </summary>
        public static string LIFESTYLE_Description {
            get {
                return ResourceManager.GetString("LIFESTYLE_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifestyle &amp; Values.
        /// </summary>
        public static string LIFESTYLE_ShortName {
            get {
                return ResourceManager.GetString("LIFESTYLE_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dating Profile &amp; Relationship Tips: Personality.
        /// </summary>
        public static string PERSONALITY {
            get {
                return ResourceManager.GetString("PERSONALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how personality, communication, money habits, love languages and intimacy preferences can influence relationships..
        /// </summary>
        public static string PERSONALITY_Description {
            get {
                return ResourceManager.GetString("PERSONALITY_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personality.
        /// </summary>
        public static string PERSONALITY_ShortName {
            get {
                return ResourceManager.GetString("PERSONALITY_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dating Profile &amp; Relationship Tips: Relationship Preferences.
        /// </summary>
        public static string RELATIONSHIP {
            get {
                return ResourceManager.GetString("RELATIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore finances, conflict resolution, household roles, time together and boundaries that can affect relationship compatibility..
        /// </summary>
        public static string RELATIONSHIP_Description {
            get {
                return ResourceManager.GetString("RELATIONSHIP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Preferences.
        /// </summary>
        public static string RELATIONSHIP_ShortName {
            get {
                return ResourceManager.GetString("RELATIONSHIP_ShortName", resourceCulture);
            }
        }
    }
}
