//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Translations.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FamilyInvolvement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FamilyInvolvement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Translations.Enum.FamilyInvolvement", typeof(FamilyInvolvement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My family is deeply involved and has a strong influence on my relationship and marriage decisions..
        /// </summary>
        public static string HeavilyInvolved_Description {
            get {
                return ResourceManager.GetString("HeavilyInvolved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavily Involved.
        /// </summary>
        public static string HeavilyInvolved_Name {
            get {
                return ResourceManager.GetString("HeavilyInvolved_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My family does not participate in my relationship or marriage decisions..
        /// </summary>
        public static string NotInvolved_Description {
            get {
                return ResourceManager.GetString("NotInvolved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Involved.
        /// </summary>
        public static string NotInvolved_Name {
            get {
                return ResourceManager.GetString("NotInvolved_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My family participates and provides input, but the final decision is mine..
        /// </summary>
        public static string SomeInvolvement_Description {
            get {
                return ResourceManager.GetString("SomeInvolvement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Involvement.
        /// </summary>
        public static string SomeInvolvement_Name {
            get {
                return ResourceManager.GetString("SomeInvolvement_Name", resourceCulture);
            }
        }
    }
}
