//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.Shared.Translations.Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HavePets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HavePets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.Shared.Translations.Enum.HavePets", typeof(HavePets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat(s).
        /// </summary>
        public static string Cat {
            get {
                return ResourceManager.GetString("Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have cat(s) (e.g., Persian, Siamese, Maine Coon)..
        /// </summary>
        public static string Cat_Description {
            get {
                return ResourceManager.GetString("Cat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog(s).
        /// </summary>
        public static string Dog {
            get {
                return ResourceManager.GetString("Dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have dog(s) (e.g., Labrador, Poodle, Bulldog)..
        /// </summary>
        public static string Dog_Description {
            get {
                return ResourceManager.GetString("Dog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog(s) and Cat(s).
        /// </summary>
        public static string DogCat {
            get {
                return ResourceManager.GetString("DogCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have both dog(s) and cat(s)..
        /// </summary>
        public static string DogCat_Description {
            get {
                return ResourceManager.GetString("DogCat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exotic Pets.
        /// </summary>
        public static string ExoticPets {
            get {
                return ResourceManager.GetString("ExoticPets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have exotic pets (e.g., snakes, lizards, ferrets, fish, or tarantulas)..
        /// </summary>
        public static string ExoticPets_Description {
            get {
                return ResourceManager.GetString("ExoticPets_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Don’t Have.
        /// </summary>
        public static string IDontHave {
            get {
                return ResourceManager.GetString("IDontHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I currently don’t own any pets..
        /// </summary>
        public static string IDontHave_Description {
            get {
                return ResourceManager.GetString("IDontHave_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Don’t Want.
        /// </summary>
        public static string IDontWant {
            get {
                return ResourceManager.GetString("IDontWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don’t have pets and prefer not to have any..
        /// </summary>
        public static string IDontWant_Description {
            get {
                return ResourceManager.GetString("IDontWant_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Pets.
        /// </summary>
        public static string SmallPets {
            get {
                return ResourceManager.GetString("SmallPets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have small pets (e.g., rabbits, hamsters, guinea pigs, or birds)..
        /// </summary>
        public static string SmallPets_Description {
            get {
                return ResourceManager.GetString("SmallPets_Description", resourceCulture);
            }
        }
    }
}
